package org.gtkkn.gir.model

data class GirClass(
    val info: GirInfo,
    val name: String,
    val glibTypeName: String,
    val glibGetType: String,
    val parent: String?,
    val glibTypeStruct: String?,
    val glibRefFunc: String?,
    val glibUnrefFunc: String?,
    val glibSetValueFunc: String?,
    val glibGetValueFunc: String?,
    val cType: String?,
    val cSymbolPrefix: String?,
    val abstract: Boolean?,
    val glibFundamental: Boolean?,
    val final: Boolean?,
    val implements: List<GirImplements>,
    val constructors: List<GirConstructor>,
    val methods: List<GirMethod>,
    val functions: List<GirFunction>,
    val virtualMethods: List<GirVirtualMethod>,
    val fields: List<GirField>,
    val properties: List<GirProperty>,
    val signals: List<GirSignal>,
    val unions: List<GirUnion>,
    val constants: List<GirConstant>,
    val records: List<GirRecord>,
    val callbacks: List<GirCallback>,
)
