# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# pip install -r mkdocs-requirements.txt
# mkdocs serve

# Project information
site_name: gtk-kn
site_url: https://gtk-kn.org
site_description: "Kotlin/Native bindings for the GTK framework and other GObject-Introspection-based libraries."
site_author: gtk-kn
site_dir: public

# Repository
repo_name: gtk-kn
repo_url: https://gitlab.com/gtk-kn/gtk-kn
edit_uri: edit/master/docs/

# Page tree
nav:
  - Home: index.md
  - Get Started: get-started/index.md
  - Developer Guide:
      - developer-guide/index.md
      - Environment Setup: developer-guide/environment-setup.md
      - Gradle plugin: developer-guide/gradle-plugin.md
      - Logging: developer-guide/logging.md
      #      - GObject Concepts: developer-guide/gobject-concepts.md
      #      - Main Event Loop: developer-guide/the-main-event-loop.md
      - UI Design: developer-guide/ui-design.md
      - Bindings:
          - developer-guide/bindings/index.md
          - GTK4:
              - developer-guide/bindings/gtk4/index.md
              - Widgets:
                  - developer-guide/bindings/gtk4/widgets/index.md
                  - Gallery: developer-guide/bindings/gtk4/widgets/visual-index.md
                  - Examples:
                      - Label: developer-guide/bindings/gtk4/widgets/examples/label.md
                      - ProgressBar: developer-guide/bindings/gtk4/widgets/examples/progress-bar.md
                      - Spinner: developer-guide/bindings/gtk4/widgets/examples/spinner.md
          #          - Clipboard: developer-guide/bindings/gtk4/clipboard.md
          #          - Drag and Drop: developer-guide/bindings/gtk4/drag-and-drop.md
          #          - Actions: developer-guide/bindings/gtk4/actions.md
          #          - Menus: developer-guide/bindings/gtk4/menus.md
          - GIO:
              - developer-guide/bindings/gio/index.md
              #          - File operations: developer-guide/bindings/gio/file-operations.md
              - Notifications: developer-guide/bindings/gio/notifications.md
          #          - Settings: developer-guide/bindings/gio/settings.md
          - Adwaita:
              - developer-guide/bindings/adwaita/index.md
          #          - Examples:
          #              - Boxed lists: developer-guide/bindings/adwaita/examples/boxed-lists.md
          #              - Sidebar: developer-guide/bindings/adwaita/examples/sidebar.md
          #              - Placeholder page: developer-guide/bindings/adwaita/examples/placeholder-page.md
          #              - Collections: developer-guide/bindings/adwaita/examples/collections.md
          #              - Window: developer-guide/bindings/adwaita/examples/window.md
          #              - Leaflet and Dialog: developer-guide/bindings/adwaita/examples/leaflet-and-dialog.md
          - GtkSourceView:
              - developer-guide/bindings/gtksource/index.md
          - WebKitGTK:
              - developer-guide/bindings/webkitgtk/index.md
      #      - Tutorials:
      #          - Text viewer: user-guide/tutorials/text-viewer.md
  - Contributor Guide:
      - contributor-guide/index.md
      - Deploying to MavenLocal: contributor-guide/deploying-to-mavenlocal.md
      #      - MkDocs: contributor-guide/mkdocs.md
      #      - CI and Docker images: contributor-guide/ci-and-docker-images.md
  - API: dokka/index.html
  - FAQ: faq/index.md
  - Sponsor: sponsor/index.md
  - Contact: contact-us/index.md

# Copyright
copyright: >
  Copyright &copy; 2025 gtk-kn –
  <a href="#__consent">Change cookie settings</a>

# Configuration
theme:
  name: 'material'
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: custom
      accent: 'deep-purple'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: custom
      accent: 'blue-grey'
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: 'assets/logo-icon.svg'
  favicon: 'assets/favicon.ico'

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  - social

# Customization
extra_css:
  - assets/stylesheets/extra.css
extra:
  social:
    - icon: simple/matrix
      link: https://matrix.to/#/#gtk-kn:matrix.org
      name: Matrix
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/gtk-kn/
      name: GitLab
    - icon: fontawesome/brands/github
      link: https://github.com/gtk-kn/
      name: GitHub
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: '.'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - smarty
  - tables
  - toc:
      permalink: true
      toc_depth: 3
