# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# pip install -r mkdocs-requirements.txt
# mkdocs serve

# Project information
site_name: gtk-kn
site_url: https://gtk-kn.org
site_description: "Kotlin/Native bindings for the GTK framework and other GObject-Introspection-based libraries."
site_author: gtk-kn
site_dir: public

# Repository
repo_name: gtk-kn
repo_url: https://gitlab.com/gtk-kn/gtk-kn
edit_uri: edit/master/docs/

# Page tree
nav:
  - Home:
      - index.md
      #      - Change Log: changelog.md
  - Get Started: get-started/index.md
  - User guide:
      - user-guide/index.md
      - Installation: user-guide/installation.md
      - Deploy on MavenLocal: user-guide/deploy-on-mavenlocal.md
      - K/N project setup: user-guide/project-setup.md
      - Hello World!: user-guide/hello-world.md
      #      - GObject concepts: user-guide/gobject-concepts.md
      #      - The main event loop: user-guide/the-main-event-loop.md
      - Gradle plugin: user-guide/gradle-plugin.md
      - Logging: user-guide/logging.md
      - GTK4:
          - user-guide/gtk4/index.md
          - Widgets:
              - user-guide/gtk4/widgets/index.md
              - Gallery: user-guide/gtk4/widgets/visual-index.md
              - Examples:
                  - Label: user-guide/gtk4/widgets/examples/label.md
                  - ProgressBar: user-guide/gtk4/widgets/examples/progress-bar.md
                  - Spinner: user-guide/gtk4/widgets/examples/spinner.md
      #          - Clipboard: user-guide/gtk4/clipboard.md
      #          - Drag and Drop: user-guide/gtk4/drag-and-drop.md
      #          - Actions: user-guide/gtk4/actions.md
      #          - Menus: user-guide/gtk4/menus.md
      - GIO:
          - user-guide/gio/index.md
          #          - File operations: user-guide/gio/file-operations.md
          - Notifications: user-guide/gio/notifications.md
      #          - Settings: user-guide/gio/settings.md
      - Adwaita:
          - user-guide/adwaita/index.md
      #          - Examples:
      #              - Boxed lists: user-guide/adwaita/examples/boxed-lists.md
      #              - Sidebar: user-guide/adwaita/examples/sidebar.md
      #              - Placeholder page: user-guide/adwaita/examples/placeholder-page.md
      #              - Collections: user-guide/adwaita/examples/collections.md
      #              - Window: user-guide/adwaita/examples/window.md
      #              - Leaflet and Dialog: user-guide/adwaita/examples/leaflet-and-dialog.md
      #      - Tutorials:
      #          - Text viewer: user-guide/tutorials/text-viewer.md
      - Optional bindings:
          - user-guide/optional-bindings/index.md
          - GtkSourceView: user-guide/optional-bindings/gtksource/index.md
          - WebKitGTK: user-guide/optional-bindings/webkitgtk/index.md
  #      - Tutorials:
  #          - Text viewer: user-guide/tutorials/text-viewer.md
  - FAQ: faq/index.md
  - Contributing: contributing/index.md
  - API: dokka/index.html

# Copyright
copyright: >
  Copyright &copy; 2025 gtk-kn –
  <a href="#__consent">Change cookie settings</a>

# Configuration
theme:
  name: 'material'
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: custom
      accent: 'deep-purple'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'black'
      accent: 'blue-grey'
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: 'assets/logo.svg'
  favicon: 'assets/favicon.ico'

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  - social

# Customization
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: simple/matrix
      link: https://matrix.to/#/#gtk-kn:matrix.org
      name: Matrix
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/gtk-kn/
      name: GitLab
    - icon: fontawesome/brands/github
      link: https://github.com/gtk-kn/
      name: GitHub
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - md_in_html
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: '.'
  - pymdownx.superfences
  - smarty
  - tables
  - toc:
      permalink: true
