// This is a generated file. Do not modify.
package org.gtkkn.bindings.adw

import org.gtkkn.extensions.gobject.KGType
import org.gtkkn.extensions.gobject.TypeProvider
import kotlin.collections.Map
import kotlin.reflect.KClass

public object AdwTypeProvider : TypeProvider {
    override val typeMap: Map<KClass<*>, KGType<*>> =
        mapOf(
            AboutDialog::class to AboutDialog.type,
            AboutWindow::class to AboutWindow.type,
            ActionRow::class to ActionRow.type,
            AlertDialog::class to AlertDialog.type,
            Animation::class to Animation.type,
            AnimationTarget::class to AnimationTarget.type,
            Application::class to Application.type,
            ApplicationWindow::class to ApplicationWindow.type,
            Avatar::class to Avatar.type,
            Banner::class to Banner.type,
            Bin::class to Bin.type,
            Breakpoint::class to Breakpoint.type,
            BreakpointBin::class to BreakpointBin.type,
            ButtonContent::class to ButtonContent.type,
            CallbackAnimationTarget::class to CallbackAnimationTarget.type,
            Carousel::class to Carousel.type,
            CarouselIndicatorDots::class to CarouselIndicatorDots.type,
            CarouselIndicatorLines::class to CarouselIndicatorLines.type,
            Clamp::class to Clamp.type,
            ClampLayout::class to ClampLayout.type,
            ClampScrollable::class to ClampScrollable.type,
            ComboRow::class to ComboRow.type,
            Dialog::class to Dialog.type,
            EntryRow::class to EntryRow.type,
            EnumListItem::class to EnumListItem.type,
            EnumListModel::class to EnumListModel.type,
            ExpanderRow::class to ExpanderRow.type,
            Flap::class to Flap.type,
            HeaderBar::class to HeaderBar.type,
            Leaflet::class to Leaflet.type,
            LeafletPage::class to LeafletPage.type,
            MessageDialog::class to MessageDialog.type,
            NavigationPage::class to NavigationPage.type,
            NavigationSplitView::class to NavigationSplitView.type,
            NavigationView::class to NavigationView.type,
            OverlaySplitView::class to OverlaySplitView.type,
            PasswordEntryRow::class to PasswordEntryRow.type,
            PreferencesDialog::class to PreferencesDialog.type,
            PreferencesGroup::class to PreferencesGroup.type,
            PreferencesPage::class to PreferencesPage.type,
            PreferencesRow::class to PreferencesRow.type,
            PreferencesWindow::class to PreferencesWindow.type,
            PropertyAnimationTarget::class to PropertyAnimationTarget.type,
            SpinRow::class to SpinRow.type,
            SplitButton::class to SplitButton.type,
            SpringAnimation::class to SpringAnimation.type,
            Squeezer::class to Squeezer.type,
            SqueezerPage::class to SqueezerPage.type,
            StatusPage::class to StatusPage.type,
            StyleManager::class to StyleManager.type,
            SwipeTracker::class to SwipeTracker.type,
            SwitchRow::class to SwitchRow.type,
            TabBar::class to TabBar.type,
            TabButton::class to TabButton.type,
            TabOverview::class to TabOverview.type,
            TabPage::class to TabPage.type,
            TabView::class to TabView.type,
            TimedAnimation::class to TimedAnimation.type,
            Toast::class to Toast.type,
            ToastOverlay::class to ToastOverlay.type,
            ToolbarView::class to ToolbarView.type,
            ViewStack::class to ViewStack.type,
            ViewStackPage::class to ViewStackPage.type,
            ViewStackPages::class to ViewStackPages.type,
            ViewSwitcher::class to ViewSwitcher.type,
            ViewSwitcherBar::class to ViewSwitcherBar.type,
            ViewSwitcherTitle::class to ViewSwitcherTitle.type,
            Window::class to Window.type,
            WindowTitle::class to WindowTitle.type,
            Swipeable::class to Swipeable.type,
        )
}
