// This is a generated file. Do not modify.
// Copyright (c) 2025 gtk-kn
// SPDX-License-Identifier: LGPL-2.1-or-later
package org.gtkkn.gradle.plugin.config

import kotlin.Pair
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlin.collections.Map

@Suppress("all")
internal val repositoryAnnotations: Map<String, List<Pair<String, String>>> = mapOf(
    "adw" to listOf(
        "1.1" to "org.gtkkn.bindings.adw.annotations.AdwVersion1_1",
        "1.2" to "org.gtkkn.bindings.adw.annotations.AdwVersion1_2",
        "1.3" to "org.gtkkn.bindings.adw.annotations.AdwVersion1_3",
        "1.4" to "org.gtkkn.bindings.adw.annotations.AdwVersion1_4",
        "1.5" to "org.gtkkn.bindings.adw.annotations.AdwVersion1_5",
        "1.6" to "org.gtkkn.bindings.adw.annotations.AdwVersion1_6"
    ),
    "cairo" to listOf(
        "1.10" to "org.gtkkn.bindings.cairo.annotations.CairoVersion1_10",
        "1.12" to "org.gtkkn.bindings.cairo.annotations.CairoVersion1_12",
        "1.14" to "org.gtkkn.bindings.cairo.annotations.CairoVersion1_14",
        "1.16" to "org.gtkkn.bindings.cairo.annotations.CairoVersion1_16",
        "1.18" to "org.gtkkn.bindings.cairo.annotations.CairoVersion1_18",
        "1.2" to "org.gtkkn.bindings.cairo.annotations.CairoVersion1_2",
        "1.4" to "org.gtkkn.bindings.cairo.annotations.CairoVersion1_4",
        "1.6" to "org.gtkkn.bindings.cairo.annotations.CairoVersion1_6",
        "1.8" to "org.gtkkn.bindings.cairo.annotations.CairoVersion1_8"
    ),
    "gdkpixbuf" to listOf(
        "2.12" to "org.gtkkn.bindings.gdk.annotations.GdkPixbufVersion2_12",
        "2.14" to "org.gtkkn.bindings.gdk.annotations.GdkPixbufVersion2_14",
        "2.18" to "org.gtkkn.bindings.gdk.annotations.GdkPixbufVersion2_18",
        "2.2" to "org.gtkkn.bindings.gdk.annotations.GdkPixbufVersion2_2",
        "2.22" to "org.gtkkn.bindings.gdk.annotations.GdkPixbufVersion2_22",
        "2.24" to "org.gtkkn.bindings.gdk.annotations.GdkPixbufVersion2_24",
        "2.26" to "org.gtkkn.bindings.gdk.annotations.GdkPixbufVersion2_26",
        "2.28" to "org.gtkkn.bindings.gdk.annotations.GdkPixbufVersion2_28",
        "2.30" to "org.gtkkn.bindings.gdk.annotations.GdkPixbufVersion2_30",
        "2.32" to "org.gtkkn.bindings.gdk.annotations.GdkPixbufVersion2_32",
        "2.36" to "org.gtkkn.bindings.gdk.annotations.GdkPixbufVersion2_36",
        "2.36.8" to "org.gtkkn.bindings.gdk.annotations.GdkPixbufVersion2_36_8",
        "2.4" to "org.gtkkn.bindings.gdk.annotations.GdkPixbufVersion2_4",
        "2.40" to "org.gtkkn.bindings.gdk.annotations.GdkPixbufVersion2_40",
        "2.6" to "org.gtkkn.bindings.gdk.annotations.GdkPixbufVersion2_6",
        "2.8" to "org.gtkkn.bindings.gdk.annotations.GdkPixbufVersion2_8"
    ),
    "gdk" to listOf(
        "4.10" to "org.gtkkn.bindings.gdk.annotations.GdkVersion4_10",
        "4.12" to "org.gtkkn.bindings.gdk.annotations.GdkVersion4_12",
        "4.14" to "org.gtkkn.bindings.gdk.annotations.GdkVersion4_14",
        "4.16" to "org.gtkkn.bindings.gdk.annotations.GdkVersion4_16",
        "4.2" to "org.gtkkn.bindings.gdk.annotations.GdkVersion4_2",
        "4.4" to "org.gtkkn.bindings.gdk.annotations.GdkVersion4_4",
        "4.6" to "org.gtkkn.bindings.gdk.annotations.GdkVersion4_6",
        "4.8" to "org.gtkkn.bindings.gdk.annotations.GdkVersion4_8"
    ),
    "gio" to listOf(
        "2.18" to "org.gtkkn.bindings.gio.annotations.GioVersion2_18",
        "2.20" to "org.gtkkn.bindings.gio.annotations.GioVersion2_20",
        "2.22" to "org.gtkkn.bindings.gio.annotations.GioVersion2_22",
        "2.24" to "org.gtkkn.bindings.gio.annotations.GioVersion2_24",
        "2.26" to "org.gtkkn.bindings.gio.annotations.GioVersion2_26",
        "2.28" to "org.gtkkn.bindings.gio.annotations.GioVersion2_28",
        "2.30" to "org.gtkkn.bindings.gio.annotations.GioVersion2_30",
        "2.32" to "org.gtkkn.bindings.gio.annotations.GioVersion2_32",
        "2.34" to "org.gtkkn.bindings.gio.annotations.GioVersion2_34",
        "2.36" to "org.gtkkn.bindings.gio.annotations.GioVersion2_36",
        "2.38" to "org.gtkkn.bindings.gio.annotations.GioVersion2_38",
        "2.40" to "org.gtkkn.bindings.gio.annotations.GioVersion2_40",
        "2.42" to "org.gtkkn.bindings.gio.annotations.GioVersion2_42",
        "2.44" to "org.gtkkn.bindings.gio.annotations.GioVersion2_44",
        "2.46" to "org.gtkkn.bindings.gio.annotations.GioVersion2_46",
        "2.48" to "org.gtkkn.bindings.gio.annotations.GioVersion2_48",
        "2.50" to "org.gtkkn.bindings.gio.annotations.GioVersion2_50",
        "2.52" to "org.gtkkn.bindings.gio.annotations.GioVersion2_52",
        "2.54" to "org.gtkkn.bindings.gio.annotations.GioVersion2_54",
        "2.56" to "org.gtkkn.bindings.gio.annotations.GioVersion2_56",
        "2.58" to "org.gtkkn.bindings.gio.annotations.GioVersion2_58",
        "2.60" to "org.gtkkn.bindings.gio.annotations.GioVersion2_60",
        "2.62" to "org.gtkkn.bindings.gio.annotations.GioVersion2_62",
        "2.64" to "org.gtkkn.bindings.gio.annotations.GioVersion2_64",
        "2.66" to "org.gtkkn.bindings.gio.annotations.GioVersion2_66",
        "2.68" to "org.gtkkn.bindings.gio.annotations.GioVersion2_68",
        "2.70" to "org.gtkkn.bindings.gio.annotations.GioVersion2_70",
        "2.72" to "org.gtkkn.bindings.gio.annotations.GioVersion2_72",
        "2.74" to "org.gtkkn.bindings.gio.annotations.GioVersion2_74",
        "2.76" to "org.gtkkn.bindings.gio.annotations.GioVersion2_76",
        "2.78" to "org.gtkkn.bindings.gio.annotations.GioVersion2_78",
        "2.80" to "org.gtkkn.bindings.gio.annotations.GioVersion2_80",
        "2.82" to "org.gtkkn.bindings.gio.annotations.GioVersion2_82"
    ),
    "glib" to listOf(
        "2.10" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_10",
        "2.12" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_12",
        "2.14" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_14",
        "2.16" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_16",
        "2.18" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_18",
        "2.2" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_2",
        "2.20" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_20",
        "2.22" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_22",
        "2.24" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_24",
        "2.26" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_26",
        "2.28" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_28",
        "2.30" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_30",
        "2.32" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_32",
        "2.34" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_34",
        "2.36" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_36",
        "2.38" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_38",
        "2.4" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_4",
        "2.40" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_40",
        "2.44" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_44",
        "2.46" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_46",
        "2.48" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_48",
        "2.50" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_50",
        "2.52" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_52",
        "2.54" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_54",
        "2.56" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_56",
        "2.58" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_58",
        "2.6" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_6",
        "2.60" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_60",
        "2.62" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_62",
        "2.64" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_64",
        "2.66" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_66",
        "2.68" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_68",
        "2.70" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_70",
        "2.72" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_72",
        "2.74" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_74",
        "2.76" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_76",
        "2.78" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_78",
        "2.8" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_8",
        "2.80" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_80",
        "2.82" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_82"
    ),
    "gmodule" to listOf(
        "2.70" to "org.gtkkn.bindings.gmodule.annotations.GModuleVersion2_70"
    ),
    "gobject" to listOf(
        "2.10" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_10",
        "2.12" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_12",
        "2.24" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_24",
        "2.26" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_26",
        "2.28" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_28",
        "2.30" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_30",
        "2.32" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_32",
        "2.34" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_34",
        "2.36" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_36",
        "2.38" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_38",
        "2.4" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_4",
        "2.42" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_42",
        "2.44" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_44",
        "2.46" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_46",
        "2.54" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_54",
        "2.6" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_6",
        "2.66" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_66",
        "2.68" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_68",
        "2.70" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_70",
        "2.72" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_72",
        "2.74" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_74",
        "2.8" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_8",
        "2.80" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_80"
    ),
    "graphene" to listOf(
        "1.0" to "org.gtkkn.bindings.graphene.annotations.GrapheneVersion1_0",
        "1.10" to "org.gtkkn.bindings.graphene.annotations.GrapheneVersion1_10",
        "1.2" to "org.gtkkn.bindings.graphene.annotations.GrapheneVersion1_2",
        "1.4" to "org.gtkkn.bindings.graphene.annotations.GrapheneVersion1_4",
        "1.6" to "org.gtkkn.bindings.graphene.annotations.GrapheneVersion1_6"
    ),
    "gsk" to listOf(
        "4.10" to "org.gtkkn.bindings.gsk.annotations.GskVersion4_10",
        "4.14" to "org.gtkkn.bindings.gsk.annotations.GskVersion4_14",
        "4.16" to "org.gtkkn.bindings.gsk.annotations.GskVersion4_16",
        "4.2" to "org.gtkkn.bindings.gsk.annotations.GskVersion4_2",
        "4.6" to "org.gtkkn.bindings.gsk.annotations.GskVersion4_6"
    ),
    "gtk" to listOf(
        "4.10" to "org.gtkkn.bindings.gtk.annotations.GtkVersion4_10",
        "4.12" to "org.gtkkn.bindings.gtk.annotations.GtkVersion4_12",
        "4.14" to "org.gtkkn.bindings.gtk.annotations.GtkVersion4_14",
        "4.16" to "org.gtkkn.bindings.gtk.annotations.GtkVersion4_16",
        "4.2" to "org.gtkkn.bindings.gtk.annotations.GtkVersion4_2",
        "4.4" to "org.gtkkn.bindings.gtk.annotations.GtkVersion4_4",
        "4.6" to "org.gtkkn.bindings.gtk.annotations.GtkVersion4_6",
        "4.8" to "org.gtkkn.bindings.gtk.annotations.GtkVersion4_8"
    ),
    "gtksource" to listOf(
        "5.10" to "org.gtkkn.bindings.gtksource.annotations.GtkSourceVersion5_10",
        "5.12" to "org.gtkkn.bindings.gtksource.annotations.GtkSourceVersion5_12",
        "5.2" to "org.gtkkn.bindings.gtksource.annotations.GtkSourceVersion5_2",
        "5.4" to "org.gtkkn.bindings.gtksource.annotations.GtkSourceVersion5_4",
        "5.6" to "org.gtkkn.bindings.gtksource.annotations.GtkSourceVersion5_6"
    ),
    "pango" to listOf(
        "1.10" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_10",
        "1.12" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_12",
        "1.14" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_14",
        "1.16" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_16",
        "1.18" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_18",
        "1.2" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_2",
        "1.20" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_20",
        "1.22" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_22",
        "1.24" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_24",
        "1.26" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_26",
        "1.30" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_30",
        "1.31.0" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_31_0",
        "1.32" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_32",
        "1.32.4" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_32_4",
        "1.34" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_34",
        "1.36.7" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_36_7",
        "1.38" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_38",
        "1.4" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_4",
        "1.42" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_42",
        "1.44" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_44",
        "1.46" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_46",
        "1.50" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_50",
        "1.52" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_52",
        "1.54" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_54",
        "1.56" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_56",
        "1.6" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_6",
        "1.8" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_8"
    ),
    "pangocairo" to listOf(
        "1.10" to "org.gtkkn.bindings.pangocairo.annotations.PangoCairoVersion1_10",
        "1.14" to "org.gtkkn.bindings.pangocairo.annotations.PangoCairoVersion1_14",
        "1.18" to "org.gtkkn.bindings.pangocairo.annotations.PangoCairoVersion1_18",
        "1.22" to "org.gtkkn.bindings.pangocairo.annotations.PangoCairoVersion1_22"
    )
)
