// This is a generated file. Do not modify.
package org.gtkkn.gradle.plugin.config

import kotlin.Pair
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlin.collections.Map

@Suppress("all")
internal val repositoryAnnotations: Map<String, List<Pair<String, String>>> = mapOf(
    "adw" to listOf(
        "1.1" to "org.gtkkn.bindings.adw.annotations.AdwVersion1_1",
        "1.2" to "org.gtkkn.bindings.adw.annotations.AdwVersion1_2",
        "1.3" to "org.gtkkn.bindings.adw.annotations.AdwVersion1_3",
        "1.4" to "org.gtkkn.bindings.adw.annotations.AdwVersion1_4",
        "1.5" to "org.gtkkn.bindings.adw.annotations.AdwVersion1_5"
    ),
    "gdk" to listOf(
        "4.10" to "org.gtkkn.bindings.gdk.annotations.GdkVersion4_10",
        "4.12" to "org.gtkkn.bindings.gdk.annotations.GdkVersion4_12",
        "4.14" to "org.gtkkn.bindings.gdk.annotations.GdkVersion4_14",
        "4.2" to "org.gtkkn.bindings.gdk.annotations.GdkVersion4_2",
        "4.4" to "org.gtkkn.bindings.gdk.annotations.GdkVersion4_4",
        "4.6" to "org.gtkkn.bindings.gdk.annotations.GdkVersion4_6",
        "4.8" to "org.gtkkn.bindings.gdk.annotations.GdkVersion4_8"
    ),
    "gdkpixbuf" to listOf(
        "GdkPixbufVersion2.12" to "org.gtkkn.bindings.gdkpixbuf.annotations.GdkPixbufVersion2_12",
        "GdkPixbufVersion2.14" to "org.gtkkn.bindings.gdkpixbuf.annotations.GdkPixbufVersion2_14",
        "GdkPixbufVersion2.18" to "org.gtkkn.bindings.gdkpixbuf.annotations.GdkPixbufVersion2_18",
        "GdkPixbufVersion2.2" to "org.gtkkn.bindings.gdkpixbuf.annotations.GdkPixbufVersion2_2",
        "GdkPixbufVersion2.22" to "org.gtkkn.bindings.gdkpixbuf.annotations.GdkPixbufVersion2_22",
        "GdkPixbufVersion2.24" to "org.gtkkn.bindings.gdkpixbuf.annotations.GdkPixbufVersion2_24",
        "GdkPixbufVersion2.26" to "org.gtkkn.bindings.gdkpixbuf.annotations.GdkPixbufVersion2_26",
        "GdkPixbufVersion2.28" to "org.gtkkn.bindings.gdkpixbuf.annotations.GdkPixbufVersion2_28",
        "GdkPixbufVersion2.30" to "org.gtkkn.bindings.gdkpixbuf.annotations.GdkPixbufVersion2_30",
        "GdkPixbufVersion2.32" to "org.gtkkn.bindings.gdkpixbuf.annotations.GdkPixbufVersion2_32",
        "GdkPixbufVersion2.36" to "org.gtkkn.bindings.gdkpixbuf.annotations.GdkPixbufVersion2_36",
        "GdkPixbufVersion2.36.8" to "org.gtkkn.bindings.gdkpixbuf.annotations.GdkPixbufVersion2_36_8",
        "GdkPixbufVersion2.4" to "org.gtkkn.bindings.gdkpixbuf.annotations.GdkPixbufVersion2_4",
        "GdkPixbufVersion2.40" to "org.gtkkn.bindings.gdkpixbuf.annotations.GdkPixbufVersion2_40",
        "GdkPixbufVersion2.6" to "org.gtkkn.bindings.gdkpixbuf.annotations.GdkPixbufVersion2_6",
        "GdkPixbufVersion2.8" to "org.gtkkn.bindings.gdkpixbuf.annotations.GdkPixbufVersion2_8"
    ),
    "gio" to listOf(
        "2.18" to "org.gtkkn.bindings.gio.annotations.GioVersion2_18",
        "2.20" to "org.gtkkn.bindings.gio.annotations.GioVersion2_20",
        "2.22" to "org.gtkkn.bindings.gio.annotations.GioVersion2_22",
        "2.24" to "org.gtkkn.bindings.gio.annotations.GioVersion2_24",
        "2.26" to "org.gtkkn.bindings.gio.annotations.GioVersion2_26",
        "2.28" to "org.gtkkn.bindings.gio.annotations.GioVersion2_28",
        "2.30" to "org.gtkkn.bindings.gio.annotations.GioVersion2_30",
        "2.32" to "org.gtkkn.bindings.gio.annotations.GioVersion2_32",
        "2.34" to "org.gtkkn.bindings.gio.annotations.GioVersion2_34",
        "2.36" to "org.gtkkn.bindings.gio.annotations.GioVersion2_36",
        "2.38" to "org.gtkkn.bindings.gio.annotations.GioVersion2_38",
        "2.40" to "org.gtkkn.bindings.gio.annotations.GioVersion2_40",
        "2.42" to "org.gtkkn.bindings.gio.annotations.GioVersion2_42",
        "2.44" to "org.gtkkn.bindings.gio.annotations.GioVersion2_44",
        "2.46" to "org.gtkkn.bindings.gio.annotations.GioVersion2_46",
        "2.48" to "org.gtkkn.bindings.gio.annotations.GioVersion2_48",
        "2.50" to "org.gtkkn.bindings.gio.annotations.GioVersion2_50",
        "2.52" to "org.gtkkn.bindings.gio.annotations.GioVersion2_52",
        "2.54" to "org.gtkkn.bindings.gio.annotations.GioVersion2_54",
        "2.56" to "org.gtkkn.bindings.gio.annotations.GioVersion2_56",
        "2.58" to "org.gtkkn.bindings.gio.annotations.GioVersion2_58",
        "2.60" to "org.gtkkn.bindings.gio.annotations.GioVersion2_60",
        "2.62" to "org.gtkkn.bindings.gio.annotations.GioVersion2_62",
        "2.64" to "org.gtkkn.bindings.gio.annotations.GioVersion2_64",
        "2.66" to "org.gtkkn.bindings.gio.annotations.GioVersion2_66",
        "2.68" to "org.gtkkn.bindings.gio.annotations.GioVersion2_68",
        "2.70" to "org.gtkkn.bindings.gio.annotations.GioVersion2_70",
        "2.72" to "org.gtkkn.bindings.gio.annotations.GioVersion2_72",
        "2.74" to "org.gtkkn.bindings.gio.annotations.GioVersion2_74",
        "2.76" to "org.gtkkn.bindings.gio.annotations.GioVersion2_76",
        "2.78" to "org.gtkkn.bindings.gio.annotations.GioVersion2_78",
        "2.80" to "org.gtkkn.bindings.gio.annotations.GioVersion2_80"
    ),
    "glib" to listOf(
        "GLibVersion2.10" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_10",
        "GLibVersion2.12" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_12",
        "GLibVersion2.14" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_14",
        "GLibVersion2.16" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_16",
        "GLibVersion2.18" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_18",
        "GLibVersion2.2" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_2",
        "GLibVersion2.20" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_20",
        "GLibVersion2.22" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_22",
        "GLibVersion2.24" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_24",
        "GLibVersion2.26" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_26",
        "GLibVersion2.28" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_28",
        "GLibVersion2.30" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_30",
        "GLibVersion2.32" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_32",
        "GLibVersion2.34" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_34",
        "GLibVersion2.36" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_36",
        "GLibVersion2.38" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_38",
        "GLibVersion2.4" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_4",
        "GLibVersion2.40" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_40",
        "GLibVersion2.44" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_44",
        "GLibVersion2.46" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_46",
        "GLibVersion2.48" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_48",
        "GLibVersion2.50" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_50",
        "GLibVersion2.52" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_52",
        "GLibVersion2.54" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_54",
        "GLibVersion2.56" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_56",
        "GLibVersion2.58" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_58",
        "GLibVersion2.6" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_6",
        "GLibVersion2.60" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_60",
        "GLibVersion2.62" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_62",
        "GLibVersion2.64" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_64",
        "GLibVersion2.66" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_66",
        "GLibVersion2.68" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_68",
        "GLibVersion2.70" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_70",
        "GLibVersion2.72" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_72",
        "GLibVersion2.74" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_74",
        "GLibVersion2.76" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_76",
        "GLibVersion2.78" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_78",
        "GLibVersion2.8" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_8",
        "GLibVersion2.80" to "org.gtkkn.bindings.glib.annotations.GLibVersion2_80"
    ),
    "gmodule" to listOf(
        "GModuleVersion2.70" to "org.gtkkn.bindings.gmodule.annotations.GModuleVersion2_70"
    ),
    "gobject" to listOf(
        "GObjectVersion2.10" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_10",
        "GObjectVersion2.12" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_12",
        "GObjectVersion2.24" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_24",
        "GObjectVersion2.26" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_26",
        "GObjectVersion2.28" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_28",
        "GObjectVersion2.32" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_32",
        "GObjectVersion2.34" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_34",
        "GObjectVersion2.36" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_36",
        "GObjectVersion2.38" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_38",
        "GObjectVersion2.4" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_4",
        "GObjectVersion2.42" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_42",
        "GObjectVersion2.44" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_44",
        "GObjectVersion2.46" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_46",
        "GObjectVersion2.54" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_54",
        "GObjectVersion2.6" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_6",
        "GObjectVersion2.66" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_66",
        "GObjectVersion2.68" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_68",
        "GObjectVersion2.70" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_70",
        "GObjectVersion2.72" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_72",
        "GObjectVersion2.74" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_74",
        "GObjectVersion2.8" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_8",
        "GObjectVersion2.80" to "org.gtkkn.bindings.gobject.annotations.GObjectVersion2_80"
    ),
    "graphene" to listOf(
        "1.0" to "org.gtkkn.bindings.graphene.annotations.GrapheneVersion1_0",
        "1.10" to "org.gtkkn.bindings.graphene.annotations.GrapheneVersion1_10",
        "1.2" to "org.gtkkn.bindings.graphene.annotations.GrapheneVersion1_2",
        "1.4" to "org.gtkkn.bindings.graphene.annotations.GrapheneVersion1_4",
        "1.6" to "org.gtkkn.bindings.graphene.annotations.GrapheneVersion1_6"
    ),
    "gsk" to listOf(
        "4.10" to "org.gtkkn.bindings.gsk.annotations.GskVersion4_10",
        "4.14" to "org.gtkkn.bindings.gsk.annotations.GskVersion4_14",
        "4.2" to "org.gtkkn.bindings.gsk.annotations.GskVersion4_2",
        "4.6" to "org.gtkkn.bindings.gsk.annotations.GskVersion4_6"
    ),
    "gtk" to listOf(
        "4.10" to "org.gtkkn.bindings.gtk.annotations.GtkVersion4_10",
        "4.12" to "org.gtkkn.bindings.gtk.annotations.GtkVersion4_12",
        "4.14" to "org.gtkkn.bindings.gtk.annotations.GtkVersion4_14",
        "4.2" to "org.gtkkn.bindings.gtk.annotations.GtkVersion4_2",
        "4.4" to "org.gtkkn.bindings.gtk.annotations.GtkVersion4_4",
        "4.6" to "org.gtkkn.bindings.gtk.annotations.GtkVersion4_6",
        "4.8" to "org.gtkkn.bindings.gtk.annotations.GtkVersion4_8"
    ),
    "pango" to listOf(
        "1.10" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_10",
        "1.12" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_12",
        "1.14" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_14",
        "1.16" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_16",
        "1.18" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_18",
        "1.2" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_2",
        "1.20" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_20",
        "1.22" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_22",
        "1.24" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_24",
        "1.26" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_26",
        "1.30" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_30",
        "1.31.0" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_31_0",
        "1.32" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_32",
        "1.32.4" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_32_4",
        "1.34" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_34",
        "1.36.7" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_36_7",
        "1.38" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_38",
        "1.4" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_4",
        "1.42" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_42",
        "1.44" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_44",
        "1.46" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_46",
        "1.50" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_50",
        "1.52" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_52",
        "1.54" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_54",
        "1.6" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_6",
        "1.8" to "org.gtkkn.bindings.pango.annotations.PangoVersion1_8"
    ),
    "pangocairo" to listOf(
        "PangoCairoVersion1.10" to "org.gtkkn.bindings.pangocairo.annotations.PangoCairoVersion1_10",
        "PangoCairoVersion1.18" to "org.gtkkn.bindings.pangocairo.annotations.PangoCairoVersion1_18",
        "PangoCairoVersion1.22" to "org.gtkkn.bindings.pangocairo.annotations.PangoCairoVersion1_22"
    )
)
