// This is a generated file. Do not modify.
package org.gtkkn.gradle.plugin.config

import kotlin.Pair
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlin.collections.Map

@Suppress("all")
internal val repositoryAnnotations: Map<String, List<Pair<String, String>>> =
    mapOf(
        "adw" to
            listOf(
                "1.1" to "ORG.GTKKN.BINDINGS.ADW.ANNOTATIONS.ADWVERSION1_1",
                "1.2" to "ORG.GTKKN.BINDINGS.ADW.ANNOTATIONS.ADWVERSION1_2",
                "1.3" to "ORG.GTKKN.BINDINGS.ADW.ANNOTATIONS.ADWVERSION1_3",
                "1.4" to "ORG.GTKKN.BINDINGS.ADW.ANNOTATIONS.ADWVERSION1_4",
                "1.5" to "ORG.GTKKN.BINDINGS.ADW.ANNOTATIONS.ADWVERSION1_5"
            ),
        "gdk" to
            listOf(
                "4.10" to "ORG.GTKKN.BINDINGS.GDK.ANNOTATIONS.GDKVERSION4_10",
                "4.12" to "ORG.GTKKN.BINDINGS.GDK.ANNOTATIONS.GDKVERSION4_12",
                "4.14" to "ORG.GTKKN.BINDINGS.GDK.ANNOTATIONS.GDKVERSION4_14",
                "4.2" to "ORG.GTKKN.BINDINGS.GDK.ANNOTATIONS.GDKVERSION4_2",
                "4.4" to "ORG.GTKKN.BINDINGS.GDK.ANNOTATIONS.GDKVERSION4_4",
                "4.6" to "ORG.GTKKN.BINDINGS.GDK.ANNOTATIONS.GDKVERSION4_6",
                "4.8" to "ORG.GTKKN.BINDINGS.GDK.ANNOTATIONS.GDKVERSION4_8"
            ),
        "gdkpixbuf" to
            listOf(
                "GDKPIXBUFVERSION2.12" to "ORG.GTKKN.BINDINGS.GDKPIXBUF.ANNOTATIONS.GDKPIXBUFVERSION2_12",
                "GDKPIXBUFVERSION2.14" to "ORG.GTKKN.BINDINGS.GDKPIXBUF.ANNOTATIONS.GDKPIXBUFVERSION2_14",
                "GDKPIXBUFVERSION2.18" to "ORG.GTKKN.BINDINGS.GDKPIXBUF.ANNOTATIONS.GDKPIXBUFVERSION2_18",
                "GDKPIXBUFVERSION2.2" to "ORG.GTKKN.BINDINGS.GDKPIXBUF.ANNOTATIONS.GDKPIXBUFVERSION2_2",
                "GDKPIXBUFVERSION2.22" to "ORG.GTKKN.BINDINGS.GDKPIXBUF.ANNOTATIONS.GDKPIXBUFVERSION2_22",
                "GDKPIXBUFVERSION2.24" to "ORG.GTKKN.BINDINGS.GDKPIXBUF.ANNOTATIONS.GDKPIXBUFVERSION2_24",
                "GDKPIXBUFVERSION2.26" to "ORG.GTKKN.BINDINGS.GDKPIXBUF.ANNOTATIONS.GDKPIXBUFVERSION2_26",
                "GDKPIXBUFVERSION2.28" to "ORG.GTKKN.BINDINGS.GDKPIXBUF.ANNOTATIONS.GDKPIXBUFVERSION2_28",
                "GDKPIXBUFVERSION2.30" to "ORG.GTKKN.BINDINGS.GDKPIXBUF.ANNOTATIONS.GDKPIXBUFVERSION2_30",
                "GDKPIXBUFVERSION2.32" to "ORG.GTKKN.BINDINGS.GDKPIXBUF.ANNOTATIONS.GDKPIXBUFVERSION2_32",
                "GDKPIXBUFVERSION2.36" to "ORG.GTKKN.BINDINGS.GDKPIXBUF.ANNOTATIONS.GDKPIXBUFVERSION2_36",
                "GDKPIXBUFVERSION2.36.8" to "ORG.GTKKN.BINDINGS.GDKPIXBUF.ANNOTATIONS.GDKPIXBUFVERSION2_36_8",
                "GDKPIXBUFVERSION2.4" to "ORG.GTKKN.BINDINGS.GDKPIXBUF.ANNOTATIONS.GDKPIXBUFVERSION2_4",
                "GDKPIXBUFVERSION2.40" to "ORG.GTKKN.BINDINGS.GDKPIXBUF.ANNOTATIONS.GDKPIXBUFVERSION2_40",
                "GDKPIXBUFVERSION2.6" to "ORG.GTKKN.BINDINGS.GDKPIXBUF.ANNOTATIONS.GDKPIXBUFVERSION2_6",
                "GDKPIXBUFVERSION2.8" to "ORG.GTKKN.BINDINGS.GDKPIXBUF.ANNOTATIONS.GDKPIXBUFVERSION2_8"
            ),
        "gio" to
            listOf(
                "2.18" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_18",
                "2.20" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_20",
                "2.22" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_22",
                "2.24" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_24",
                "2.26" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_26",
                "2.28" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_28",
                "2.30" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_30",
                "2.32" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_32",
                "2.34" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_34",
                "2.36" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_36",
                "2.38" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_38",
                "2.40" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_40",
                "2.42" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_42",
                "2.44" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_44",
                "2.46" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_46",
                "2.48" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_48",
                "2.50" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_50",
                "2.52" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_52",
                "2.54" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_54",
                "2.56" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_56",
                "2.58" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_58",
                "2.60" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_60",
                "2.62" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_62",
                "2.64" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_64",
                "2.66" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_66",
                "2.68" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_68",
                "2.70" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_70",
                "2.72" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_72",
                "2.74" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_74",
                "2.76" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_76",
                "2.78" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_78",
                "2.80" to "ORG.GTKKN.BINDINGS.GIO.ANNOTATIONS.GIOVERSION2_80"
            ),
        "glib" to
            listOf(
                "GLIBVERSION2.10" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_10",
                "GLIBVERSION2.12" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_12",
                "GLIBVERSION2.14" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_14",
                "GLIBVERSION2.16" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_16",
                "GLIBVERSION2.18" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_18",
                "GLIBVERSION2.2" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_2",
                "GLIBVERSION2.20" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_20",
                "GLIBVERSION2.22" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_22",
                "GLIBVERSION2.24" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_24",
                "GLIBVERSION2.26" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_26",
                "GLIBVERSION2.28" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_28",
                "GLIBVERSION2.30" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_30",
                "GLIBVERSION2.32" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_32",
                "GLIBVERSION2.34" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_34",
                "GLIBVERSION2.36" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_36",
                "GLIBVERSION2.38" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_38",
                "GLIBVERSION2.4" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_4",
                "GLIBVERSION2.40" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_40",
                "GLIBVERSION2.44" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_44",
                "GLIBVERSION2.46" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_46",
                "GLIBVERSION2.50" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_50",
                "GLIBVERSION2.52" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_52",
                "GLIBVERSION2.54" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_54",
                "GLIBVERSION2.56" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_56",
                "GLIBVERSION2.58" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_58",
                "GLIBVERSION2.6" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_6",
                "GLIBVERSION2.60" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_60",
                "GLIBVERSION2.62" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_62",
                "GLIBVERSION2.64" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_64",
                "GLIBVERSION2.66" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_66",
                "GLIBVERSION2.68" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_68",
                "GLIBVERSION2.70" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_70",
                "GLIBVERSION2.72" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_72",
                "GLIBVERSION2.74" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_74",
                "GLIBVERSION2.76" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_76",
                "GLIBVERSION2.78" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_78",
                "GLIBVERSION2.8" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_8",
                "GLIBVERSION2.80" to "ORG.GTKKN.BINDINGS.GLIB.ANNOTATIONS.GLIBVERSION2_80"
            ),
        "gmodule" to
            listOf(
                "GMODULEVERSION2.70" to "ORG.GTKKN.BINDINGS.GMODULE.ANNOTATIONS.GMODULEVERSION2_70"
            ),
        "gobject" to
            listOf(
                "GOBJECTVERSION2.10" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_10",
                "GOBJECTVERSION2.12" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_12",
                "GOBJECTVERSION2.24" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_24",
                "GOBJECTVERSION2.26" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_26",
                "GOBJECTVERSION2.32" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_32",
                "GOBJECTVERSION2.34" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_34",
                "GOBJECTVERSION2.36" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_36",
                "GOBJECTVERSION2.38" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_38",
                "GOBJECTVERSION2.4" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_4",
                "GOBJECTVERSION2.42" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_42",
                "GOBJECTVERSION2.44" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_44",
                "GOBJECTVERSION2.46" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_46",
                "GOBJECTVERSION2.6" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_6",
                "GOBJECTVERSION2.66" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_66",
                "GOBJECTVERSION2.68" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_68",
                "GOBJECTVERSION2.72" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_72",
                "GOBJECTVERSION2.74" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_74",
                "GOBJECTVERSION2.80" to "ORG.GTKKN.BINDINGS.GOBJECT.ANNOTATIONS.GOBJECTVERSION2_80"
            ),
        "graphene" to
            listOf(
                "1.0" to "ORG.GTKKN.BINDINGS.GRAPHENE.ANNOTATIONS.GRAPHENEVERSION1_0",
                "1.10" to "ORG.GTKKN.BINDINGS.GRAPHENE.ANNOTATIONS.GRAPHENEVERSION1_10",
                "1.2" to "ORG.GTKKN.BINDINGS.GRAPHENE.ANNOTATIONS.GRAPHENEVERSION1_2",
                "1.4" to "ORG.GTKKN.BINDINGS.GRAPHENE.ANNOTATIONS.GRAPHENEVERSION1_4",
                "1.6" to "ORG.GTKKN.BINDINGS.GRAPHENE.ANNOTATIONS.GRAPHENEVERSION1_6"
            ),
        "gsk" to
            listOf(
                "4.10" to "ORG.GTKKN.BINDINGS.GSK.ANNOTATIONS.GSKVERSION4_10",
                "4.14" to "ORG.GTKKN.BINDINGS.GSK.ANNOTATIONS.GSKVERSION4_14",
                "4.2" to "ORG.GTKKN.BINDINGS.GSK.ANNOTATIONS.GSKVERSION4_2",
                "4.6" to "ORG.GTKKN.BINDINGS.GSK.ANNOTATIONS.GSKVERSION4_6"
            ),
        "gtk" to
            listOf(
                "4.10" to "ORG.GTKKN.BINDINGS.GTK.ANNOTATIONS.GTKVERSION4_10",
                "4.12" to "ORG.GTKKN.BINDINGS.GTK.ANNOTATIONS.GTKVERSION4_12",
                "4.14" to "ORG.GTKKN.BINDINGS.GTK.ANNOTATIONS.GTKVERSION4_14",
                "4.2" to "ORG.GTKKN.BINDINGS.GTK.ANNOTATIONS.GTKVERSION4_2",
                "4.4" to "ORG.GTKKN.BINDINGS.GTK.ANNOTATIONS.GTKVERSION4_4",
                "4.6" to "ORG.GTKKN.BINDINGS.GTK.ANNOTATIONS.GTKVERSION4_6",
                "4.8" to "ORG.GTKKN.BINDINGS.GTK.ANNOTATIONS.GTKVERSION4_8"
            ),
        "gtksource" to
            listOf(
                "GTKSOURCEVERSION5.10" to "ORG.GTKKN.BINDINGS.GTKSOURCE.ANNOTATIONS.GTKSOURCEVERSION5_10",
                "GTKSOURCEVERSION5.12" to "ORG.GTKKN.BINDINGS.GTKSOURCE.ANNOTATIONS.GTKSOURCEVERSION5_12",
                "GTKSOURCEVERSION5.2" to "ORG.GTKKN.BINDINGS.GTKSOURCE.ANNOTATIONS.GTKSOURCEVERSION5_2",
                "GTKSOURCEVERSION5.4" to "ORG.GTKKN.BINDINGS.GTKSOURCE.ANNOTATIONS.GTKSOURCEVERSION5_4",
                "GTKSOURCEVERSION5.6" to "ORG.GTKKN.BINDINGS.GTKSOURCE.ANNOTATIONS.GTKSOURCEVERSION5_6"
            ),
        "javascriptcore" to
            listOf(
                "JAVASCRIPTCOREVERSION2.24" to "ORG.GTKKN.BINDINGS.JAVASCRIPTCORE.ANNOTATIONS.JAVASCRIPTCOREVERSION2_24",
                "JAVASCRIPTCOREVERSION2.28" to "ORG.GTKKN.BINDINGS.JAVASCRIPTCORE.ANNOTATIONS.JAVASCRIPTCOREVERSION2_28",
                "JAVASCRIPTCOREVERSION2.38" to "ORG.GTKKN.BINDINGS.JAVASCRIPTCORE.ANNOTATIONS.JAVASCRIPTCOREVERSION2_38"
            ),
        "pango" to
            listOf(
                "1.10" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_10",
                "1.12" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_12",
                "1.14" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_14",
                "1.16" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_16",
                "1.18" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_18",
                "1.2" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_2",
                "1.20" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_20",
                "1.22" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_22",
                "1.24" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_24",
                "1.26" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_26",
                "1.30" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_30",
                "1.31.0" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_31_0",
                "1.32" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_32",
                "1.32.4" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_32_4",
                "1.34" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_34",
                "1.36.7" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_36_7",
                "1.38" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_38",
                "1.4" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_4",
                "1.42" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_42",
                "1.44" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_44",
                "1.46" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_46",
                "1.50" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_50",
                "1.52" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_52",
                "1.6" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_6",
                "1.8" to "ORG.GTKKN.BINDINGS.PANGO.ANNOTATIONS.PANGOVERSION1_8"
            ),
        "pangocairo" to
            listOf(
                "PANGOCAIROVERSION1.10" to "ORG.GTKKN.BINDINGS.PANGOCAIRO.ANNOTATIONS.PANGOCAIROVERSION1_10",
                "PANGOCAIROVERSION1.18" to "ORG.GTKKN.BINDINGS.PANGOCAIRO.ANNOTATIONS.PANGOCAIROVERSION1_18",
                "PANGOCAIROVERSION1.22" to "ORG.GTKKN.BINDINGS.PANGOCAIRO.ANNOTATIONS.PANGOCAIROVERSION1_22"
            ),
        "soup" to
            listOf(
                "3.2" to "ORG.GTKKN.BINDINGS.SOUP.ANNOTATIONS.SOUPVERSION3_2",
                "3.4" to "ORG.GTKKN.BINDINGS.SOUP.ANNOTATIONS.SOUPVERSION3_4"
            ),
        "webkit" to
            listOf(
                "WEBKITVERSION2.10" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_10",
                "WEBKITVERSION2.12" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_12",
                "WEBKITVERSION2.14" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_14",
                "WEBKITVERSION2.16" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_16",
                "WEBKITVERSION2.18" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_18",
                "WEBKITVERSION2.2" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_2",
                "WEBKITVERSION2.20" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_20",
                "WEBKITVERSION2.22" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_22",
                "WEBKITVERSION2.24" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_24",
                "WEBKITVERSION2.26" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_26",
                "WEBKITVERSION2.28" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_28",
                "WEBKITVERSION2.30" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_30",
                "WEBKITVERSION2.32" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_32",
                "WEBKITVERSION2.34" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_34",
                "WEBKITVERSION2.36" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_36",
                "WEBKITVERSION2.38" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_38",
                "WEBKITVERSION2.4" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_4",
                "WEBKITVERSION2.40" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_40",
                "WEBKITVERSION2.42" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_42",
                "WEBKITVERSION2.44" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_44",
                "WEBKITVERSION2.46" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_46",
                "WEBKITVERSION2.6" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_6",
                "WEBKITVERSION2.8" to "ORG.GTKKN.BINDINGS.WEBKIT.ANNOTATIONS.WEBKITVERSION2_8"
            )
    )
