// This is a generated file. Do not modify.
package org.gtkkn.bindings.harfbuzz

import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_CAPS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_LOWER_CASE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_HORIZ_KANA_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_HORIZ_KANA_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_VERT_KANA_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_VERT_KANA_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_HALF_WIDTH_TEXT
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_PROPORTIONAL_TEXT
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ASTERISK_TO_MULTIPLY_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ASTERISK_TO_MULTIPLY_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_BOX_ANNOTATION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CANONICAL_COMPOSITION_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CANONICAL_COMPOSITION_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_LAYOUT_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_LAYOUT_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_SPACING_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_SPACING_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CIRCLE_ANNOTATION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_FIVE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_FOUR
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_ONE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_THREE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_TWO
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_VERTICAL_ROMAN_CENTERED
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_VERTICAL_ROMAN_HBASELINE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_COMPATIBILITY_COMPOSITION_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_COMPATIBILITY_COMPOSITION_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_ALTERNATES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_ALTERNATES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_SWASH_ALTERNATES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_SWASH_ALTERNATES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_CURSIVE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_DECOMPOSE_DIACRITICS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_DECORATIVE_BORDERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_CJK_ROMAN
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_LOWER_CASE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_UPPER_CASE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL1
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL2
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL3
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL4
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL5
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_DIAGONAL_FRACTIONS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_DIAMOND_ANNOTATION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_DINGBATS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_DISPLAY_TEXT
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ENGRAVED_TEXT
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_EXPERT_CHARACTERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_EXPONENTS_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_EXPONENTS_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_FLEURONS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_FORM_INTERROBANG_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_FORM_INTERROBANG_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_CJK_ROMAN
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_IDEOGRAPHS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_KANA
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_CJK_ROMAN
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_IDEOGRAPHS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_TEXT
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_ONE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_THREE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_TWO
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_HIDE_DIACRITICS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_HIRAGANA_TO_KATAKANA
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_HOJO_CHARACTERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHENS_TO_EM_DASH_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHENS_TO_EM_DASH_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_EN_DASH_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_EN_DASH_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_MINUS_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_MINUS_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_FIVE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_FOUR
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_ONE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_THREE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_TWO
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ILLUMINATED_CAPS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_INEQUALITY_LIGATURES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_INEQUALITY_LIGATURES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_INFERIORS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_INITIAL_CAPS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_INITIAL_CAPS_AND_SMALL_CAPS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_INTERNATIONAL_SYMBOLS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_BOX_ANNOTATION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_CIRCLE_ANNOTATION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_ROUNDED_BOX_ANNOTATION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1978_CHARACTERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1983_CHARACTERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1990_CHARACTERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS2004_CHARACTERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_KANA_TO_ROMANIZATION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_KATAKANA_TO_HIRAGANA
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_FINAL_SWASHES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_FINAL_SWASHES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_INITIAL_SWASHES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_INITIAL_SWASHES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_LINGUISTIC_REARRANGEMENT_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_LINGUISTIC_REARRANGEMENT_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_NUMBERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_PETITE_CAPS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_SMALL_CAPS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_MATHEMATICAL_GREEK_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_MATHEMATICAL_GREEK_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_MATH_SYMBOLS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_MONOSPACED_NUMBERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_MONOSPACED_TEXT
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_NLCCHARACTERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_NON_FINAL_SWASHES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_NON_FINAL_SWASHES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_NORMAL_POSITION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_ALTERNATES
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_ANNOTATION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_CJK_ITALIC_ROMAN
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_CJK_SYMBOL_ALTERNATIVES
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_FRACTIONS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_IDEOGRAPHIC_ALTERNATIVES
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_ORNAMENTS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_RUBY_KANA
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_STYLE_OPTIONS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_STYLISTIC_ALTERNATES
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_TRANSLITERATION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ORDINALS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_PARENTHESIS_ANNOTATION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_PARTIALLY_CONNECTED
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_PERIODS_TO_ELLIPSIS_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_PERIODS_TO_ELLIPSIS_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_PERIOD_ANNOTATION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_PI_CHARACTERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_PREVENT_OVERLAP_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_PREVENT_OVERLAP_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_CJK_ROMAN
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_IDEOGRAPHS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_KANA
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_NUMBERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_TEXT
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_QUARTER_WIDTH_NUMBERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_QUARTER_WIDTH_TEXT
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_REQUIRED_LIGATURES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_REQUIRED_LIGATURES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ROMANIZATION_TO_HIRAGANA
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ROMANIZATION_TO_KATAKANA
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ROMAN_NUMERAL_ANNOTATION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_ROUNDED_BOX_ANNOTATION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_SCIENTIFIC_INFERIORS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_SHOW_DIACRITICS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_SIMPLIFIED_CHARACTERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASHED_ZERO_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASHED_ZERO_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASH_TO_DIVIDE_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASH_TO_DIVIDE_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_SMALL_CAPS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_SMART_QUOTES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_SMART_QUOTES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHT_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHT_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIVE_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIVE_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOUR_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOUR_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINE_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINE_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ONE_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ONE_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVEN_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVEN_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIX_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIX_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TEN_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TEN_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THREE_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THREE_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWO_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWO_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_SUBSTITUTE_VERTICAL_FORMS_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_SUBSTITUTE_VERTICAL_FORMS_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_SUPERIORS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_SWASH_ALTERNATES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_SWASH_ALTERNATES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_TALL_CAPS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_THIRD_WIDTH_NUMBERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_THIRD_WIDTH_TEXT
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_TITLING_CAPS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_FIVE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_FOUR
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_ONE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_THREE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_TWO
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_CHARACTERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_NAMES_CHARACTERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_TRANSCODING_COMPOSITION_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_TRANSCODING_COMPOSITION_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_UNCONNECTED
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_AND_LOWER_CASE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_NUMBERS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_PETITE_CAPS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_SMALL_CAPS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_VERTICAL_FRACTIONS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_FINAL_SWASHES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_FINAL_SWASHES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_INITIAL_SWASHES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.Companion.HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_INITIAL_SWASHES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_ABBREV_SQUARED_LIGATURES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_ABBREV_SQUARED_LIGATURES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_TYPE_FEATURES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_TYPE_FEATURES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_COMMON_LIGATURES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_COMMON_LIGATURES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_LIGATURES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_LIGATURES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_DIPHTHONG_LIGATURES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_DIPHTHONG_LIGATURES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_HISTORICAL_LIGATURES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_HISTORICAL_LIGATURES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_INVALID
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_LOGOS_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_LOGOS_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_RARE_LIGATURES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_RARE_LIGATURES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_REBUS_PICTURES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_REBUS_PICTURES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_SQUARED_LIGATURES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_SQUARED_LIGATURES_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHTEEN_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHTEEN_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ELEVEN_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ELEVEN_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIFTEEN_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIFTEEN_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOURTEEN_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOURTEEN_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINETEEN_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINETEEN_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVENTEEN_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVENTEEN_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIXTEEN_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIXTEEN_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THIRTEEN_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THIRTEEN_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWELVE_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWELVE_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWENTY_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWENTY_ON
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_SYMBOL_LIGATURES_OFF
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_selector_t.HB_AAT_LAYOUT_FEATURE_SELECTOR_SYMBOL_LIGATURES_ON

/**
 * The selectors defined for specifying AAT feature settings.
 * @since 2.2.0
 */
public enum class AatLayoutFeatureSelector(
    public val nativeValue: hb_aat_layout_feature_selector_t,
) {
    /**
     * Initial, unset feature selector
     */
    INVALID(HB_AAT_LAYOUT_FEATURE_SELECTOR_INVALID),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ALL_TYPOGRAPHIC
     */
    ALL_TYPE_FEATURES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_TYPE_FEATURES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ALL_TYPOGRAPHIC
     */
    ALL_TYPE_FEATURES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_TYPE_FEATURES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    REQUIRED_LIGATURES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_REQUIRED_LIGATURES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    REQUIRED_LIGATURES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_REQUIRED_LIGATURES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    COMMON_LIGATURES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_COMMON_LIGATURES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    COMMON_LIGATURES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_COMMON_LIGATURES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    RARE_LIGATURES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_RARE_LIGATURES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    RARE_LIGATURES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_RARE_LIGATURES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    LOGOS_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_LOGOS_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    LOGOS_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_LOGOS_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    REBUS_PICTURES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_REBUS_PICTURES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    REBUS_PICTURES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_REBUS_PICTURES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    DIPHTHONG_LIGATURES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_DIPHTHONG_LIGATURES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    DIPHTHONG_LIGATURES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_DIPHTHONG_LIGATURES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    SQUARED_LIGATURES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_SQUARED_LIGATURES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    SQUARED_LIGATURES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_SQUARED_LIGATURES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    ABBREV_SQUARED_LIGATURES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_ABBREV_SQUARED_LIGATURES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    ABBREV_SQUARED_LIGATURES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_ABBREV_SQUARED_LIGATURES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    SYMBOL_LIGATURES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_SYMBOL_LIGATURES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    SYMBOL_LIGATURES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_SYMBOL_LIGATURES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    CONTEXTUAL_LIGATURES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_LIGATURES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    CONTEXTUAL_LIGATURES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_LIGATURES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    HISTORICAL_LIGATURES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_HISTORICAL_LIGATURES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    HISTORICAL_LIGATURES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_HISTORICAL_LIGATURES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    UNCONNECTED(HB_AAT_LAYOUT_FEATURE_SELECTOR_UNCONNECTED),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    PARTIALLY_CONNECTED(HB_AAT_LAYOUT_FEATURE_SELECTOR_PARTIALLY_CONNECTED),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
     */
    CURSIVE(HB_AAT_LAYOUT_FEATURE_SELECTOR_CURSIVE),

    /**
     * Deprecated
     */
    UPPER_AND_LOWER_CASE(HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_AND_LOWER_CASE),

    /**
     * Deprecated
     */
    ALL_CAPS(HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_CAPS),

    /**
     * Deprecated
     */
    ALL_LOWER_CASE(HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_LOWER_CASE),

    /**
     * Deprecated
     */
    SMALL_CAPS(HB_AAT_LAYOUT_FEATURE_SELECTOR_SMALL_CAPS),

    /**
     * Deprecated
     */
    INITIAL_CAPS(HB_AAT_LAYOUT_FEATURE_SELECTOR_INITIAL_CAPS),

    /**
     * Deprecated
     */
    INITIAL_CAPS_AND_SMALL_CAPS(HB_AAT_LAYOUT_FEATURE_SELECTOR_INITIAL_CAPS_AND_SMALL_CAPS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION
     */
    SUBSTITUTE_VERTICAL_FORMS_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_SUBSTITUTE_VERTICAL_FORMS_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION
     */
    SUBSTITUTE_VERTICAL_FORMS_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_SUBSTITUTE_VERTICAL_FORMS_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LINGUISTIC_REARRANGEMENT
     */
    LINGUISTIC_REARRANGEMENT_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_LINGUISTIC_REARRANGEMENT_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LINGUISTIC_REARRANGEMENT
     */
    LINGUISTIC_REARRANGEMENT_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_LINGUISTIC_REARRANGEMENT_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING
     */
    MONOSPACED_NUMBERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_MONOSPACED_NUMBERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING
     */
    PROPORTIONAL_NUMBERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_NUMBERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING
     */
    THIRD_WIDTH_NUMBERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_THIRD_WIDTH_NUMBERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING
     */
    QUARTER_WIDTH_NUMBERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_QUARTER_WIDTH_NUMBERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
     */
    WORD_INITIAL_SWASHES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_INITIAL_SWASHES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
     */
    WORD_INITIAL_SWASHES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_INITIAL_SWASHES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
     */
    WORD_FINAL_SWASHES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_FINAL_SWASHES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
     */
    WORD_FINAL_SWASHES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_FINAL_SWASHES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
     */
    LINE_INITIAL_SWASHES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_INITIAL_SWASHES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
     */
    LINE_INITIAL_SWASHES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_INITIAL_SWASHES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
     */
    LINE_FINAL_SWASHES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_FINAL_SWASHES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
     */
    LINE_FINAL_SWASHES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_FINAL_SWASHES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
     */
    NON_FINAL_SWASHES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_NON_FINAL_SWASHES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
     */
    NON_FINAL_SWASHES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_NON_FINAL_SWASHES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_DIACRITICS_TYPE
     */
    SHOW_DIACRITICS(HB_AAT_LAYOUT_FEATURE_SELECTOR_SHOW_DIACRITICS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_DIACRITICS_TYPE
     */
    HIDE_DIACRITICS(HB_AAT_LAYOUT_FEATURE_SELECTOR_HIDE_DIACRITICS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_DIACRITICS_TYPE
     */
    DECOMPOSE_DIACRITICS(HB_AAT_LAYOUT_FEATURE_SELECTOR_DECOMPOSE_DIACRITICS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION
     */
    NORMAL_POSITION(HB_AAT_LAYOUT_FEATURE_SELECTOR_NORMAL_POSITION),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION
     */
    SUPERIORS(HB_AAT_LAYOUT_FEATURE_SELECTOR_SUPERIORS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION
     */
    INFERIORS(HB_AAT_LAYOUT_FEATURE_SELECTOR_INFERIORS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION
     */
    ORDINALS(HB_AAT_LAYOUT_FEATURE_SELECTOR_ORDINALS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION
     */
    SCIENTIFIC_INFERIORS(HB_AAT_LAYOUT_FEATURE_SELECTOR_SCIENTIFIC_INFERIORS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_FRACTIONS
     */
    NO_FRACTIONS(HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_FRACTIONS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_FRACTIONS
     */
    VERTICAL_FRACTIONS(HB_AAT_LAYOUT_FEATURE_SELECTOR_VERTICAL_FRACTIONS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_FRACTIONS
     */
    DIAGONAL_FRACTIONS(HB_AAT_LAYOUT_FEATURE_SELECTOR_DIAGONAL_FRACTIONS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_OVERLAPPING_CHARACTERS_TYPE
     */
    PREVENT_OVERLAP_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_PREVENT_OVERLAP_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_OVERLAPPING_CHARACTERS_TYPE
     */
    PREVENT_OVERLAP_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_PREVENT_OVERLAP_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
     */
    HYPHENS_TO_EM_DASH_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHENS_TO_EM_DASH_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
     */
    HYPHENS_TO_EM_DASH_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHENS_TO_EM_DASH_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
     */
    HYPHEN_TO_EN_DASH_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_EN_DASH_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
     */
    HYPHEN_TO_EN_DASH_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_EN_DASH_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
     */
    SLASHED_ZERO_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASHED_ZERO_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
     */
    SLASHED_ZERO_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASHED_ZERO_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
     */
    FORM_INTERROBANG_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_FORM_INTERROBANG_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
     */
    FORM_INTERROBANG_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_FORM_INTERROBANG_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
     */
    SMART_QUOTES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_SMART_QUOTES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
     */
    SMART_QUOTES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_SMART_QUOTES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
     */
    PERIODS_TO_ELLIPSIS_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_PERIODS_TO_ELLIPSIS_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
     */
    PERIODS_TO_ELLIPSIS_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_PERIODS_TO_ELLIPSIS_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
     */
    HYPHEN_TO_MINUS_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_MINUS_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
     */
    HYPHEN_TO_MINUS_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_MINUS_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
     */
    ASTERISK_TO_MULTIPLY_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_ASTERISK_TO_MULTIPLY_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
     */
    ASTERISK_TO_MULTIPLY_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_ASTERISK_TO_MULTIPLY_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
     */
    SLASH_TO_DIVIDE_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASH_TO_DIVIDE_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
     */
    SLASH_TO_DIVIDE_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASH_TO_DIVIDE_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
     */
    INEQUALITY_LIGATURES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_INEQUALITY_LIGATURES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
     */
    INEQUALITY_LIGATURES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_INEQUALITY_LIGATURES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
     */
    EXPONENTS_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_EXPONENTS_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
     */
    EXPONENTS_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_EXPONENTS_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
     */
    MATHEMATICAL_GREEK_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_MATHEMATICAL_GREEK_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
     */
    MATHEMATICAL_GREEK_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_MATHEMATICAL_GREEK_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE
     */
    NO_ORNAMENTS(HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_ORNAMENTS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE
     */
    DINGBATS(HB_AAT_LAYOUT_FEATURE_SELECTOR_DINGBATS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE
     */
    PI_CHARACTERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_PI_CHARACTERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE
     */
    FLEURONS(HB_AAT_LAYOUT_FEATURE_SELECTOR_FLEURONS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE
     */
    DECORATIVE_BORDERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_DECORATIVE_BORDERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE
     */
    INTERNATIONAL_SYMBOLS(HB_AAT_LAYOUT_FEATURE_SELECTOR_INTERNATIONAL_SYMBOLS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE
     */
    MATH_SYMBOLS(HB_AAT_LAYOUT_FEATURE_SELECTOR_MATH_SYMBOLS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_ALTERNATIVES
     */
    NO_ALTERNATES(HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_ALTERNATES),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE
     */
    DESIGN_LEVEL1(HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL1),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE
     */
    DESIGN_LEVEL2(HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL2),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE
     */
    DESIGN_LEVEL3(HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL3),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE
     */
    DESIGN_LEVEL4(HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL4),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE
     */
    DESIGN_LEVEL5(HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL5),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS
     */
    NO_STYLE_OPTIONS(HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_STYLE_OPTIONS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS
     */
    DISPLAY_TEXT(HB_AAT_LAYOUT_FEATURE_SELECTOR_DISPLAY_TEXT),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS
     */
    ENGRAVED_TEXT(HB_AAT_LAYOUT_FEATURE_SELECTOR_ENGRAVED_TEXT),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS
     */
    ILLUMINATED_CAPS(HB_AAT_LAYOUT_FEATURE_SELECTOR_ILLUMINATED_CAPS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS
     */
    TITLING_CAPS(HB_AAT_LAYOUT_FEATURE_SELECTOR_TITLING_CAPS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS
     */
    TALL_CAPS(HB_AAT_LAYOUT_FEATURE_SELECTOR_TALL_CAPS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
     */
    TRADITIONAL_CHARACTERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_CHARACTERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
     */
    SIMPLIFIED_CHARACTERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_SIMPLIFIED_CHARACTERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
     */
    JIS1978_CHARACTERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1978_CHARACTERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
     */
    JIS1983_CHARACTERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1983_CHARACTERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
     */
    JIS1990_CHARACTERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1990_CHARACTERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
     */
    TRADITIONAL_ALT_ONE(HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_ONE),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
     */
    TRADITIONAL_ALT_TWO(HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_TWO),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
     */
    TRADITIONAL_ALT_THREE(HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_THREE),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
     */
    TRADITIONAL_ALT_FOUR(HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_FOUR),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
     */
    TRADITIONAL_ALT_FIVE(HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_FIVE),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
     */
    EXPERT_CHARACTERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_EXPERT_CHARACTERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
     */
    JIS2004_CHARACTERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS2004_CHARACTERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
     */
    HOJO_CHARACTERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_HOJO_CHARACTERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
     */
    NLCCHARACTERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_NLCCHARACTERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
     */
    TRADITIONAL_NAMES_CHARACTERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_NAMES_CHARACTERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_CASE
     */
    LOWER_CASE_NUMBERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_NUMBERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_CASE
     */
    UPPER_CASE_NUMBERS(HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_NUMBERS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING
     */
    PROPORTIONAL_TEXT(HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_TEXT),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING
     */
    MONOSPACED_TEXT(HB_AAT_LAYOUT_FEATURE_SELECTOR_MONOSPACED_TEXT),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING
     */
    HALF_WIDTH_TEXT(HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_TEXT),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING
     */
    THIRD_WIDTH_TEXT(HB_AAT_LAYOUT_FEATURE_SELECTOR_THIRD_WIDTH_TEXT),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING
     */
    QUARTER_WIDTH_TEXT(HB_AAT_LAYOUT_FEATURE_SELECTOR_QUARTER_WIDTH_TEXT),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING
     */
    ALT_PROPORTIONAL_TEXT(HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_PROPORTIONAL_TEXT),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING
     */
    ALT_HALF_WIDTH_TEXT(HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_HALF_WIDTH_TEXT),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
     */
    NO_TRANSLITERATION(HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_TRANSLITERATION),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
     */
    HANJA_TO_HANGUL(HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
     */
    HIRAGANA_TO_KATAKANA(HB_AAT_LAYOUT_FEATURE_SELECTOR_HIRAGANA_TO_KATAKANA),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
     */
    KATAKANA_TO_HIRAGANA(HB_AAT_LAYOUT_FEATURE_SELECTOR_KATAKANA_TO_HIRAGANA),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
     */
    KANA_TO_ROMANIZATION(HB_AAT_LAYOUT_FEATURE_SELECTOR_KANA_TO_ROMANIZATION),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
     */
    ROMANIZATION_TO_HIRAGANA(HB_AAT_LAYOUT_FEATURE_SELECTOR_ROMANIZATION_TO_HIRAGANA),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
     */
    ROMANIZATION_TO_KATAKANA(HB_AAT_LAYOUT_FEATURE_SELECTOR_ROMANIZATION_TO_KATAKANA),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
     */
    HANJA_TO_HANGUL_ALT_ONE(HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_ONE),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
     */
    HANJA_TO_HANGUL_ALT_TWO(HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_TWO),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
     */
    HANJA_TO_HANGUL_ALT_THREE(HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_THREE),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
     */
    NO_ANNOTATION(HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_ANNOTATION),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
     */
    BOX_ANNOTATION(HB_AAT_LAYOUT_FEATURE_SELECTOR_BOX_ANNOTATION),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
     */
    ROUNDED_BOX_ANNOTATION(HB_AAT_LAYOUT_FEATURE_SELECTOR_ROUNDED_BOX_ANNOTATION),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
     */
    CIRCLE_ANNOTATION(HB_AAT_LAYOUT_FEATURE_SELECTOR_CIRCLE_ANNOTATION),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
     */
    INVERTED_CIRCLE_ANNOTATION(HB_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_CIRCLE_ANNOTATION),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
     */
    PARENTHESIS_ANNOTATION(HB_AAT_LAYOUT_FEATURE_SELECTOR_PARENTHESIS_ANNOTATION),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
     */
    PERIOD_ANNOTATION(HB_AAT_LAYOUT_FEATURE_SELECTOR_PERIOD_ANNOTATION),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
     */
    ROMAN_NUMERAL_ANNOTATION(HB_AAT_LAYOUT_FEATURE_SELECTOR_ROMAN_NUMERAL_ANNOTATION),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
     */
    DIAMOND_ANNOTATION(HB_AAT_LAYOUT_FEATURE_SELECTOR_DIAMOND_ANNOTATION),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
     */
    INVERTED_BOX_ANNOTATION(HB_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_BOX_ANNOTATION),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
     */
    INVERTED_ROUNDED_BOX_ANNOTATION(HB_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_ROUNDED_BOX_ANNOTATION),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_KANA_SPACING_TYPE
     */
    FULL_WIDTH_KANA(HB_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_KANA),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_KANA_SPACING_TYPE
     */
    PROPORTIONAL_KANA(HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_KANA),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_SPACING_TYPE
     */
    FULL_WIDTH_IDEOGRAPHS(HB_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_IDEOGRAPHS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_SPACING_TYPE
     */
    PROPORTIONAL_IDEOGRAPHS(HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_IDEOGRAPHS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_SPACING_TYPE
     */
    HALF_WIDTH_IDEOGRAPHS(HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_IDEOGRAPHS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE
     */
    CANONICAL_COMPOSITION_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_CANONICAL_COMPOSITION_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE
     */
    CANONICAL_COMPOSITION_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_CANONICAL_COMPOSITION_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE
     */
    COMPATIBILITY_COMPOSITION_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_COMPATIBILITY_COMPOSITION_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE
     */
    COMPATIBILITY_COMPOSITION_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_COMPATIBILITY_COMPOSITION_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE
     */
    TRANSCODING_COMPOSITION_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_TRANSCODING_COMPOSITION_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE
     */
    TRANSCODING_COMPOSITION_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_TRANSCODING_COMPOSITION_OFF),

    /**
     * Deprecated; use #HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_OFF instead
     */
    NO_RUBY_KANA(HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_RUBY_KANA),

    /**
     * Deprecated; use #HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_ON instead
     */
    RUBY_KANA(HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_RUBY_KANA
     */
    RUBY_KANA_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_RUBY_KANA
     */
    RUBY_KANA_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE
     */
    NO_CJK_SYMBOL_ALTERNATIVES(HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_CJK_SYMBOL_ALTERNATIVES),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE
     */
    CJK_SYMBOL_ALT_ONE(HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_ONE),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE
     */
    CJK_SYMBOL_ALT_TWO(HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_TWO),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE
     */
    CJK_SYMBOL_ALT_THREE(HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_THREE),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE
     */
    CJK_SYMBOL_ALT_FOUR(HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_FOUR),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE
     */
    CJK_SYMBOL_ALT_FIVE(HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_FIVE),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE
     */
    NO_IDEOGRAPHIC_ALTERNATIVES(HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_IDEOGRAPHIC_ALTERNATIVES),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE
     */
    IDEOGRAPHIC_ALT_ONE(HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_ONE),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE
     */
    IDEOGRAPHIC_ALT_TWO(HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_TWO),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE
     */
    IDEOGRAPHIC_ALT_THREE(HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_THREE),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE
     */
    IDEOGRAPHIC_ALT_FOUR(HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_FOUR),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE
     */
    IDEOGRAPHIC_ALT_FIVE(HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_FIVE),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_VERTICAL_ROMAN_PLACEMENT_TYPE
     */
    CJK_VERTICAL_ROMAN_CENTERED(HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_VERTICAL_ROMAN_CENTERED),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_VERTICAL_ROMAN_PLACEMENT_TYPE
     */
    CJK_VERTICAL_ROMAN_HBASELINE(HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_VERTICAL_ROMAN_HBASELINE),

    /**
     * Deprecated; use #HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_OFF instead
     */
    NO_CJK_ITALIC_ROMAN(HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_CJK_ITALIC_ROMAN),

    /**
     * Deprecated; use #HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_ON instead
     */
    CJK_ITALIC_ROMAN(HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ITALIC_CJK_ROMAN
     */
    CJK_ITALIC_ROMAN_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ITALIC_CJK_ROMAN
     */
    CJK_ITALIC_ROMAN_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT
     */
    CASE_SENSITIVE_LAYOUT_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_LAYOUT_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT
     */
    CASE_SENSITIVE_LAYOUT_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_LAYOUT_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT
     */
    CASE_SENSITIVE_SPACING_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_SPACING_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT
     */
    CASE_SENSITIVE_SPACING_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_SPACING_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA
     */
    ALTERNATE_HORIZ_KANA_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_HORIZ_KANA_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA
     */
    ALTERNATE_HORIZ_KANA_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_HORIZ_KANA_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA
     */
    ALTERNATE_VERT_KANA_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_VERT_KANA_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA
     */
    ALTERNATE_VERT_KANA_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_VERT_KANA_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    NO_STYLISTIC_ALTERNATES(HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_STYLISTIC_ALTERNATES),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_ONE_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ONE_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_ONE_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ONE_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_TWO_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWO_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_TWO_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWO_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_THREE_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THREE_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_THREE_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THREE_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_FOUR_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOUR_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_FOUR_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOUR_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_FIVE_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIVE_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_FIVE_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIVE_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_SIX_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIX_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_SIX_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIX_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_SEVEN_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVEN_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_SEVEN_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVEN_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_EIGHT_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHT_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_EIGHT_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHT_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_NINE_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINE_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_NINE_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINE_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_TEN_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TEN_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_TEN_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TEN_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_ELEVEN_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ELEVEN_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_ELEVEN_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ELEVEN_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_TWELVE_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWELVE_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_TWELVE_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWELVE_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_THIRTEEN_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THIRTEEN_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_THIRTEEN_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THIRTEEN_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_FOURTEEN_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOURTEEN_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_FOURTEEN_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOURTEEN_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_FIFTEEN_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIFTEEN_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_FIFTEEN_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIFTEEN_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_SIXTEEN_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIXTEEN_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_SIXTEEN_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIXTEEN_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_SEVENTEEN_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVENTEEN_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_SEVENTEEN_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVENTEEN_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_EIGHTEEN_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHTEEN_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_EIGHTEEN_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHTEEN_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_NINETEEN_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINETEEN_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_NINETEEN_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINETEEN_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_TWENTY_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWENTY_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
     */
    STYLISTIC_ALT_TWENTY_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWENTY_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES
     */
    CONTEXTUAL_ALTERNATES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_ALTERNATES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES
     */
    CONTEXTUAL_ALTERNATES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_ALTERNATES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES
     */
    SWASH_ALTERNATES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_SWASH_ALTERNATES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES
     */
    SWASH_ALTERNATES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_SWASH_ALTERNATES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES
     */
    CONTEXTUAL_SWASH_ALTERNATES_ON(HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_SWASH_ALTERNATES_ON),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES
     */
    CONTEXTUAL_SWASH_ALTERNATES_OFF(HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_SWASH_ALTERNATES_OFF),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LOWER_CASE
     */
    DEFAULT_LOWER_CASE(HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_LOWER_CASE),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LOWER_CASE
     */
    LOWER_CASE_SMALL_CAPS(HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_SMALL_CAPS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_LOWER_CASE
     */
    LOWER_CASE_PETITE_CAPS(HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_PETITE_CAPS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_UPPER_CASE
     */
    DEFAULT_UPPER_CASE(HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_UPPER_CASE),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_UPPER_CASE
     */
    UPPER_CASE_SMALL_CAPS(HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_SMALL_CAPS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_UPPER_CASE
     */
    UPPER_CASE_PETITE_CAPS(HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_PETITE_CAPS),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_ROMAN_SPACING_TYPE
     */
    HALF_WIDTH_CJK_ROMAN(HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_CJK_ROMAN),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_ROMAN_SPACING_TYPE
     */
    PROPORTIONAL_CJK_ROMAN(HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_CJK_ROMAN),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_ROMAN_SPACING_TYPE
     */
    DEFAULT_CJK_ROMAN(HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_CJK_ROMAN),

    /**
     * for #HB_AAT_LAYOUT_FEATURE_TYPE_CJK_ROMAN_SPACING_TYPE
     */
    FULL_WIDTH_CJK_ROMAN(HB_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_CJK_ROMAN),
    ;

    public companion object {
        public fun fromNativeValue(nativeValue: hb_aat_layout_feature_selector_t): AatLayoutFeatureSelector =
            when (nativeValue) {
                HB_AAT_LAYOUT_FEATURE_SELECTOR_INVALID -> INVALID
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_TYPE_FEATURES_ON -> ALL_TYPE_FEATURES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_TYPE_FEATURES_OFF -> ALL_TYPE_FEATURES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_REQUIRED_LIGATURES_ON -> REQUIRED_LIGATURES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_REQUIRED_LIGATURES_OFF -> REQUIRED_LIGATURES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_COMMON_LIGATURES_ON -> COMMON_LIGATURES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_COMMON_LIGATURES_OFF -> COMMON_LIGATURES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_RARE_LIGATURES_ON -> RARE_LIGATURES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_RARE_LIGATURES_OFF -> RARE_LIGATURES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_LOGOS_ON -> LOGOS_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_LOGOS_OFF -> LOGOS_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_REBUS_PICTURES_ON -> REBUS_PICTURES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_REBUS_PICTURES_OFF -> REBUS_PICTURES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_DIPHTHONG_LIGATURES_ON -> DIPHTHONG_LIGATURES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_DIPHTHONG_LIGATURES_OFF -> DIPHTHONG_LIGATURES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SQUARED_LIGATURES_ON -> SQUARED_LIGATURES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SQUARED_LIGATURES_OFF -> SQUARED_LIGATURES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ABBREV_SQUARED_LIGATURES_ON ->
                    ABBREV_SQUARED_LIGATURES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ABBREV_SQUARED_LIGATURES_OFF ->
                    ABBREV_SQUARED_LIGATURES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SYMBOL_LIGATURES_ON -> SYMBOL_LIGATURES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SYMBOL_LIGATURES_OFF -> SYMBOL_LIGATURES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_LIGATURES_ON -> CONTEXTUAL_LIGATURES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_LIGATURES_OFF -> CONTEXTUAL_LIGATURES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HISTORICAL_LIGATURES_ON -> HISTORICAL_LIGATURES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HISTORICAL_LIGATURES_OFF -> HISTORICAL_LIGATURES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_UNCONNECTED -> UNCONNECTED
                HB_AAT_LAYOUT_FEATURE_SELECTOR_PARTIALLY_CONNECTED -> PARTIALLY_CONNECTED
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CURSIVE -> CURSIVE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_AND_LOWER_CASE -> UPPER_AND_LOWER_CASE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_CAPS -> ALL_CAPS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_LOWER_CASE -> ALL_LOWER_CASE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SMALL_CAPS -> SMALL_CAPS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_INITIAL_CAPS -> INITIAL_CAPS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_INITIAL_CAPS_AND_SMALL_CAPS ->
                    INITIAL_CAPS_AND_SMALL_CAPS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SUBSTITUTE_VERTICAL_FORMS_ON ->
                    SUBSTITUTE_VERTICAL_FORMS_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SUBSTITUTE_VERTICAL_FORMS_OFF ->
                    SUBSTITUTE_VERTICAL_FORMS_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_LINGUISTIC_REARRANGEMENT_ON ->
                    LINGUISTIC_REARRANGEMENT_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_LINGUISTIC_REARRANGEMENT_OFF ->
                    LINGUISTIC_REARRANGEMENT_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_MONOSPACED_NUMBERS -> MONOSPACED_NUMBERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_NUMBERS -> PROPORTIONAL_NUMBERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_THIRD_WIDTH_NUMBERS -> THIRD_WIDTH_NUMBERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_QUARTER_WIDTH_NUMBERS -> QUARTER_WIDTH_NUMBERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_INITIAL_SWASHES_ON -> WORD_INITIAL_SWASHES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_INITIAL_SWASHES_OFF -> WORD_INITIAL_SWASHES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_FINAL_SWASHES_ON -> WORD_FINAL_SWASHES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_FINAL_SWASHES_OFF -> WORD_FINAL_SWASHES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_INITIAL_SWASHES_ON -> LINE_INITIAL_SWASHES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_INITIAL_SWASHES_OFF -> LINE_INITIAL_SWASHES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_FINAL_SWASHES_ON -> LINE_FINAL_SWASHES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_FINAL_SWASHES_OFF -> LINE_FINAL_SWASHES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_NON_FINAL_SWASHES_ON -> NON_FINAL_SWASHES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_NON_FINAL_SWASHES_OFF -> NON_FINAL_SWASHES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SHOW_DIACRITICS -> SHOW_DIACRITICS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HIDE_DIACRITICS -> HIDE_DIACRITICS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_DECOMPOSE_DIACRITICS -> DECOMPOSE_DIACRITICS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_NORMAL_POSITION -> NORMAL_POSITION
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SUPERIORS -> SUPERIORS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_INFERIORS -> INFERIORS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ORDINALS -> ORDINALS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SCIENTIFIC_INFERIORS -> SCIENTIFIC_INFERIORS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_FRACTIONS -> NO_FRACTIONS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_VERTICAL_FRACTIONS -> VERTICAL_FRACTIONS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_DIAGONAL_FRACTIONS -> DIAGONAL_FRACTIONS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_PREVENT_OVERLAP_ON -> PREVENT_OVERLAP_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_PREVENT_OVERLAP_OFF -> PREVENT_OVERLAP_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHENS_TO_EM_DASH_ON -> HYPHENS_TO_EM_DASH_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHENS_TO_EM_DASH_OFF -> HYPHENS_TO_EM_DASH_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_EN_DASH_ON -> HYPHEN_TO_EN_DASH_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_EN_DASH_OFF -> HYPHEN_TO_EN_DASH_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASHED_ZERO_ON -> SLASHED_ZERO_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASHED_ZERO_OFF -> SLASHED_ZERO_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_FORM_INTERROBANG_ON -> FORM_INTERROBANG_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_FORM_INTERROBANG_OFF -> FORM_INTERROBANG_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SMART_QUOTES_ON -> SMART_QUOTES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SMART_QUOTES_OFF -> SMART_QUOTES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_PERIODS_TO_ELLIPSIS_ON -> PERIODS_TO_ELLIPSIS_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_PERIODS_TO_ELLIPSIS_OFF -> PERIODS_TO_ELLIPSIS_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_MINUS_ON -> HYPHEN_TO_MINUS_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_MINUS_OFF -> HYPHEN_TO_MINUS_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ASTERISK_TO_MULTIPLY_ON -> ASTERISK_TO_MULTIPLY_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ASTERISK_TO_MULTIPLY_OFF -> ASTERISK_TO_MULTIPLY_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASH_TO_DIVIDE_ON -> SLASH_TO_DIVIDE_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASH_TO_DIVIDE_OFF -> SLASH_TO_DIVIDE_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_INEQUALITY_LIGATURES_ON -> INEQUALITY_LIGATURES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_INEQUALITY_LIGATURES_OFF -> INEQUALITY_LIGATURES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_EXPONENTS_ON -> EXPONENTS_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_EXPONENTS_OFF -> EXPONENTS_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_MATHEMATICAL_GREEK_ON -> MATHEMATICAL_GREEK_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_MATHEMATICAL_GREEK_OFF -> MATHEMATICAL_GREEK_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_ORNAMENTS -> NO_ORNAMENTS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_DINGBATS -> DINGBATS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_PI_CHARACTERS -> PI_CHARACTERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_FLEURONS -> FLEURONS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_DECORATIVE_BORDERS -> DECORATIVE_BORDERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_INTERNATIONAL_SYMBOLS -> INTERNATIONAL_SYMBOLS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_MATH_SYMBOLS -> MATH_SYMBOLS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_ALTERNATES -> NO_ALTERNATES
                HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL1 -> DESIGN_LEVEL1
                HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL2 -> DESIGN_LEVEL2
                HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL3 -> DESIGN_LEVEL3
                HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL4 -> DESIGN_LEVEL4
                HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL5 -> DESIGN_LEVEL5
                HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_STYLE_OPTIONS -> NO_STYLE_OPTIONS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_DISPLAY_TEXT -> DISPLAY_TEXT
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ENGRAVED_TEXT -> ENGRAVED_TEXT
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ILLUMINATED_CAPS -> ILLUMINATED_CAPS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_TITLING_CAPS -> TITLING_CAPS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_TALL_CAPS -> TALL_CAPS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_CHARACTERS -> TRADITIONAL_CHARACTERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SIMPLIFIED_CHARACTERS -> SIMPLIFIED_CHARACTERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1978_CHARACTERS -> JIS1978_CHARACTERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1983_CHARACTERS -> JIS1983_CHARACTERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1990_CHARACTERS -> JIS1990_CHARACTERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_ONE -> TRADITIONAL_ALT_ONE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_TWO -> TRADITIONAL_ALT_TWO
                HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_THREE -> TRADITIONAL_ALT_THREE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_FOUR -> TRADITIONAL_ALT_FOUR
                HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_FIVE -> TRADITIONAL_ALT_FIVE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_EXPERT_CHARACTERS -> EXPERT_CHARACTERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS2004_CHARACTERS -> JIS2004_CHARACTERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HOJO_CHARACTERS -> HOJO_CHARACTERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_NLCCHARACTERS -> NLCCHARACTERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_NAMES_CHARACTERS ->
                    TRADITIONAL_NAMES_CHARACTERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_NUMBERS -> LOWER_CASE_NUMBERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_NUMBERS -> UPPER_CASE_NUMBERS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_TEXT -> PROPORTIONAL_TEXT
                HB_AAT_LAYOUT_FEATURE_SELECTOR_MONOSPACED_TEXT -> MONOSPACED_TEXT
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_TEXT -> HALF_WIDTH_TEXT
                HB_AAT_LAYOUT_FEATURE_SELECTOR_THIRD_WIDTH_TEXT -> THIRD_WIDTH_TEXT
                HB_AAT_LAYOUT_FEATURE_SELECTOR_QUARTER_WIDTH_TEXT -> QUARTER_WIDTH_TEXT
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_PROPORTIONAL_TEXT -> ALT_PROPORTIONAL_TEXT
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_HALF_WIDTH_TEXT -> ALT_HALF_WIDTH_TEXT
                HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_TRANSLITERATION -> NO_TRANSLITERATION
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL -> HANJA_TO_HANGUL
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HIRAGANA_TO_KATAKANA -> HIRAGANA_TO_KATAKANA
                HB_AAT_LAYOUT_FEATURE_SELECTOR_KATAKANA_TO_HIRAGANA -> KATAKANA_TO_HIRAGANA
                HB_AAT_LAYOUT_FEATURE_SELECTOR_KANA_TO_ROMANIZATION -> KANA_TO_ROMANIZATION
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ROMANIZATION_TO_HIRAGANA -> ROMANIZATION_TO_HIRAGANA
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ROMANIZATION_TO_KATAKANA -> ROMANIZATION_TO_KATAKANA
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_ONE -> HANJA_TO_HANGUL_ALT_ONE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_TWO -> HANJA_TO_HANGUL_ALT_TWO
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_THREE -> HANJA_TO_HANGUL_ALT_THREE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_ANNOTATION -> NO_ANNOTATION
                HB_AAT_LAYOUT_FEATURE_SELECTOR_BOX_ANNOTATION -> BOX_ANNOTATION
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ROUNDED_BOX_ANNOTATION -> ROUNDED_BOX_ANNOTATION
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CIRCLE_ANNOTATION -> CIRCLE_ANNOTATION
                HB_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_CIRCLE_ANNOTATION -> INVERTED_CIRCLE_ANNOTATION
                HB_AAT_LAYOUT_FEATURE_SELECTOR_PARENTHESIS_ANNOTATION -> PARENTHESIS_ANNOTATION
                HB_AAT_LAYOUT_FEATURE_SELECTOR_PERIOD_ANNOTATION -> PERIOD_ANNOTATION
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ROMAN_NUMERAL_ANNOTATION -> ROMAN_NUMERAL_ANNOTATION
                HB_AAT_LAYOUT_FEATURE_SELECTOR_DIAMOND_ANNOTATION -> DIAMOND_ANNOTATION
                HB_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_BOX_ANNOTATION -> INVERTED_BOX_ANNOTATION
                HB_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_ROUNDED_BOX_ANNOTATION ->
                    INVERTED_ROUNDED_BOX_ANNOTATION
                HB_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_KANA -> FULL_WIDTH_KANA
                HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_KANA -> PROPORTIONAL_KANA
                HB_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_IDEOGRAPHS -> FULL_WIDTH_IDEOGRAPHS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_IDEOGRAPHS -> PROPORTIONAL_IDEOGRAPHS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_IDEOGRAPHS -> HALF_WIDTH_IDEOGRAPHS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CANONICAL_COMPOSITION_ON -> CANONICAL_COMPOSITION_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CANONICAL_COMPOSITION_OFF -> CANONICAL_COMPOSITION_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_COMPATIBILITY_COMPOSITION_ON ->
                    COMPATIBILITY_COMPOSITION_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_COMPATIBILITY_COMPOSITION_OFF ->
                    COMPATIBILITY_COMPOSITION_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_TRANSCODING_COMPOSITION_ON -> TRANSCODING_COMPOSITION_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_TRANSCODING_COMPOSITION_OFF ->
                    TRANSCODING_COMPOSITION_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_RUBY_KANA -> NO_RUBY_KANA
                HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA -> RUBY_KANA
                HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_ON -> RUBY_KANA_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_OFF -> RUBY_KANA_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_CJK_SYMBOL_ALTERNATIVES -> NO_CJK_SYMBOL_ALTERNATIVES
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_ONE -> CJK_SYMBOL_ALT_ONE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_TWO -> CJK_SYMBOL_ALT_TWO
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_THREE -> CJK_SYMBOL_ALT_THREE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_FOUR -> CJK_SYMBOL_ALT_FOUR
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_FIVE -> CJK_SYMBOL_ALT_FIVE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_IDEOGRAPHIC_ALTERNATIVES ->
                    NO_IDEOGRAPHIC_ALTERNATIVES
                HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_ONE -> IDEOGRAPHIC_ALT_ONE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_TWO -> IDEOGRAPHIC_ALT_TWO
                HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_THREE -> IDEOGRAPHIC_ALT_THREE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_FOUR -> IDEOGRAPHIC_ALT_FOUR
                HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_FIVE -> IDEOGRAPHIC_ALT_FIVE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_VERTICAL_ROMAN_CENTERED ->
                    CJK_VERTICAL_ROMAN_CENTERED
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_VERTICAL_ROMAN_HBASELINE ->
                    CJK_VERTICAL_ROMAN_HBASELINE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_CJK_ITALIC_ROMAN -> NO_CJK_ITALIC_ROMAN
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN -> CJK_ITALIC_ROMAN
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_ON -> CJK_ITALIC_ROMAN_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_OFF -> CJK_ITALIC_ROMAN_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_LAYOUT_ON -> CASE_SENSITIVE_LAYOUT_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_LAYOUT_OFF -> CASE_SENSITIVE_LAYOUT_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_SPACING_ON -> CASE_SENSITIVE_SPACING_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_SPACING_OFF -> CASE_SENSITIVE_SPACING_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_HORIZ_KANA_ON -> ALTERNATE_HORIZ_KANA_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_HORIZ_KANA_OFF -> ALTERNATE_HORIZ_KANA_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_VERT_KANA_ON -> ALTERNATE_VERT_KANA_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_VERT_KANA_OFF -> ALTERNATE_VERT_KANA_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_STYLISTIC_ALTERNATES -> NO_STYLISTIC_ALTERNATES
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ONE_ON -> STYLISTIC_ALT_ONE_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ONE_OFF -> STYLISTIC_ALT_ONE_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWO_ON -> STYLISTIC_ALT_TWO_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWO_OFF -> STYLISTIC_ALT_TWO_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THREE_ON -> STYLISTIC_ALT_THREE_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THREE_OFF -> STYLISTIC_ALT_THREE_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOUR_ON -> STYLISTIC_ALT_FOUR_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOUR_OFF -> STYLISTIC_ALT_FOUR_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIVE_ON -> STYLISTIC_ALT_FIVE_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIVE_OFF -> STYLISTIC_ALT_FIVE_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIX_ON -> STYLISTIC_ALT_SIX_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIX_OFF -> STYLISTIC_ALT_SIX_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVEN_ON -> STYLISTIC_ALT_SEVEN_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVEN_OFF -> STYLISTIC_ALT_SEVEN_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHT_ON -> STYLISTIC_ALT_EIGHT_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHT_OFF -> STYLISTIC_ALT_EIGHT_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINE_ON -> STYLISTIC_ALT_NINE_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINE_OFF -> STYLISTIC_ALT_NINE_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TEN_ON -> STYLISTIC_ALT_TEN_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TEN_OFF -> STYLISTIC_ALT_TEN_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ELEVEN_ON -> STYLISTIC_ALT_ELEVEN_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ELEVEN_OFF -> STYLISTIC_ALT_ELEVEN_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWELVE_ON -> STYLISTIC_ALT_TWELVE_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWELVE_OFF -> STYLISTIC_ALT_TWELVE_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THIRTEEN_ON -> STYLISTIC_ALT_THIRTEEN_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THIRTEEN_OFF -> STYLISTIC_ALT_THIRTEEN_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOURTEEN_ON -> STYLISTIC_ALT_FOURTEEN_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOURTEEN_OFF -> STYLISTIC_ALT_FOURTEEN_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIFTEEN_ON -> STYLISTIC_ALT_FIFTEEN_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIFTEEN_OFF -> STYLISTIC_ALT_FIFTEEN_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIXTEEN_ON -> STYLISTIC_ALT_SIXTEEN_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIXTEEN_OFF -> STYLISTIC_ALT_SIXTEEN_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVENTEEN_ON -> STYLISTIC_ALT_SEVENTEEN_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVENTEEN_OFF ->
                    STYLISTIC_ALT_SEVENTEEN_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHTEEN_ON -> STYLISTIC_ALT_EIGHTEEN_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHTEEN_OFF -> STYLISTIC_ALT_EIGHTEEN_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINETEEN_ON -> STYLISTIC_ALT_NINETEEN_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINETEEN_OFF -> STYLISTIC_ALT_NINETEEN_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWENTY_ON -> STYLISTIC_ALT_TWENTY_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWENTY_OFF -> STYLISTIC_ALT_TWENTY_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_ALTERNATES_ON -> CONTEXTUAL_ALTERNATES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_ALTERNATES_OFF -> CONTEXTUAL_ALTERNATES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SWASH_ALTERNATES_ON -> SWASH_ALTERNATES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_SWASH_ALTERNATES_OFF -> SWASH_ALTERNATES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_SWASH_ALTERNATES_ON ->
                    CONTEXTUAL_SWASH_ALTERNATES_ON
                HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_SWASH_ALTERNATES_OFF ->
                    CONTEXTUAL_SWASH_ALTERNATES_OFF
                HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_LOWER_CASE -> DEFAULT_LOWER_CASE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_SMALL_CAPS -> LOWER_CASE_SMALL_CAPS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_PETITE_CAPS -> LOWER_CASE_PETITE_CAPS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_UPPER_CASE -> DEFAULT_UPPER_CASE
                HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_SMALL_CAPS -> UPPER_CASE_SMALL_CAPS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_PETITE_CAPS -> UPPER_CASE_PETITE_CAPS
                HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_CJK_ROMAN -> HALF_WIDTH_CJK_ROMAN
                HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_CJK_ROMAN -> PROPORTIONAL_CJK_ROMAN
                HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_CJK_ROMAN -> DEFAULT_CJK_ROMAN
                HB_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_CJK_ROMAN -> FULL_WIDTH_CJK_ROMAN
                else -> error("invalid nativeValue")
            }
    }
}
