// This is a generated file. Do not modify.
package org.gtkkn.bindings.harfbuzz

import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_ALL_TYPOGRAPHIC
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_ALTERNATIVES
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_CJK_ROMAN_SPACING_TYPE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_CJK_VERTICAL_ROMAN_PLACEMENT_TYPE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_CURISVE_CONNECTION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_DIACRITICS_TYPE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_FRACTIONS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_SPACING_TYPE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_INVALID
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_ITALIC_CJK_ROMAN
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_KANA_SPACING_TYPE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_LANGUAGE_TAG_TYPE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_LETTER_CASE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_LINGUISTIC_REARRANGEMENT
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_LOWER_CASE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_CASE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_OVERLAPPING_CHARACTERS_TYPE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_RUBY_KANA
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_UPPER_CASE
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION
import org.gtkkn.native.harfbuzz.hb_aat_layout_feature_type_t.HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION

/**
 * The possible feature types defined for AAT shaping.
 * @since 2.2.0
 */
public enum class AatLayoutFeatureType(
    public val nativeValue: hb_aat_layout_feature_type_t,
) {
    /**
     * Initial, unset feature type
     */
    INVALID(HB_AAT_LAYOUT_FEATURE_TYPE_INVALID),
    ALL_TYPOGRAPHIC(HB_AAT_LAYOUT_FEATURE_TYPE_ALL_TYPOGRAPHIC),
    LIGATURES(HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES),
    CURISVE_CONNECTION(HB_AAT_LAYOUT_FEATURE_TYPE_CURISVE_CONNECTION),
    LETTER_CASE(HB_AAT_LAYOUT_FEATURE_TYPE_LETTER_CASE),
    VERTICAL_SUBSTITUTION(HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION),
    LINGUISTIC_REARRANGEMENT(HB_AAT_LAYOUT_FEATURE_TYPE_LINGUISTIC_REARRANGEMENT),
    NUMBER_SPACING(HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING),
    SMART_SWASH_TYPE(HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE),
    DIACRITICS_TYPE(HB_AAT_LAYOUT_FEATURE_TYPE_DIACRITICS_TYPE),
    VERTICAL_POSITION(HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION),
    FRACTIONS(HB_AAT_LAYOUT_FEATURE_TYPE_FRACTIONS),
    OVERLAPPING_CHARACTERS_TYPE(HB_AAT_LAYOUT_FEATURE_TYPE_OVERLAPPING_CHARACTERS_TYPE),
    TYPOGRAPHIC_EXTRAS(HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS),
    MATHEMATICAL_EXTRAS(HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS),
    ORNAMENT_SETS_TYPE(HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE),
    CHARACTER_ALTERNATIVES(HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_ALTERNATIVES),
    DESIGN_COMPLEXITY_TYPE(HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE),
    STYLE_OPTIONS(HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS),
    CHARACTER_SHAPE(HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE),
    NUMBER_CASE(HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_CASE),
    TEXT_SPACING(HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING),
    TRANSLITERATION(HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION),
    ANNOTATION_TYPE(HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE),
    KANA_SPACING_TYPE(HB_AAT_LAYOUT_FEATURE_TYPE_KANA_SPACING_TYPE),
    IDEOGRAPHIC_SPACING_TYPE(HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_SPACING_TYPE),
    UNICODE_DECOMPOSITION_TYPE(HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE),
    RUBY_KANA(HB_AAT_LAYOUT_FEATURE_TYPE_RUBY_KANA),
    CJK_SYMBOL_ALTERNATIVES_TYPE(HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE),
    IDEOGRAPHIC_ALTERNATIVES_TYPE(HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE),
    CJK_VERTICAL_ROMAN_PLACEMENT_TYPE(HB_AAT_LAYOUT_FEATURE_TYPE_CJK_VERTICAL_ROMAN_PLACEMENT_TYPE),
    ITALIC_CJK_ROMAN(HB_AAT_LAYOUT_FEATURE_TYPE_ITALIC_CJK_ROMAN),
    CASE_SENSITIVE_LAYOUT(HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT),
    ALTERNATE_KANA(HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA),
    STYLISTIC_ALTERNATIVES(HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES),
    CONTEXTUAL_ALTERNATIVES(HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES),
    LOWER_CASE(HB_AAT_LAYOUT_FEATURE_TYPE_LOWER_CASE),
    UPPER_CASE(HB_AAT_LAYOUT_FEATURE_TYPE_UPPER_CASE),
    LANGUAGE_TAG_TYPE(HB_AAT_LAYOUT_FEATURE_TYPE_LANGUAGE_TAG_TYPE),
    CJK_ROMAN_SPACING_TYPE(HB_AAT_LAYOUT_FEATURE_TYPE_CJK_ROMAN_SPACING_TYPE),
    ;

    public companion object {
        public fun fromNativeValue(nativeValue: hb_aat_layout_feature_type_t): AatLayoutFeatureType =
            when (nativeValue) {
                HB_AAT_LAYOUT_FEATURE_TYPE_INVALID -> INVALID
                HB_AAT_LAYOUT_FEATURE_TYPE_ALL_TYPOGRAPHIC -> ALL_TYPOGRAPHIC
                HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES -> LIGATURES
                HB_AAT_LAYOUT_FEATURE_TYPE_CURISVE_CONNECTION -> CURISVE_CONNECTION
                HB_AAT_LAYOUT_FEATURE_TYPE_LETTER_CASE -> LETTER_CASE
                HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION -> VERTICAL_SUBSTITUTION
                HB_AAT_LAYOUT_FEATURE_TYPE_LINGUISTIC_REARRANGEMENT -> LINGUISTIC_REARRANGEMENT
                HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING -> NUMBER_SPACING
                HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE -> SMART_SWASH_TYPE
                HB_AAT_LAYOUT_FEATURE_TYPE_DIACRITICS_TYPE -> DIACRITICS_TYPE
                HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION -> VERTICAL_POSITION
                HB_AAT_LAYOUT_FEATURE_TYPE_FRACTIONS -> FRACTIONS
                HB_AAT_LAYOUT_FEATURE_TYPE_OVERLAPPING_CHARACTERS_TYPE -> OVERLAPPING_CHARACTERS_TYPE
                HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS -> TYPOGRAPHIC_EXTRAS
                HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS -> MATHEMATICAL_EXTRAS
                HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE -> ORNAMENT_SETS_TYPE
                HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_ALTERNATIVES -> CHARACTER_ALTERNATIVES
                HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE -> DESIGN_COMPLEXITY_TYPE
                HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS -> STYLE_OPTIONS
                HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE -> CHARACTER_SHAPE
                HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_CASE -> NUMBER_CASE
                HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING -> TEXT_SPACING
                HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION -> TRANSLITERATION
                HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE -> ANNOTATION_TYPE
                HB_AAT_LAYOUT_FEATURE_TYPE_KANA_SPACING_TYPE -> KANA_SPACING_TYPE
                HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_SPACING_TYPE -> IDEOGRAPHIC_SPACING_TYPE
                HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE -> UNICODE_DECOMPOSITION_TYPE
                HB_AAT_LAYOUT_FEATURE_TYPE_RUBY_KANA -> RUBY_KANA
                HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE -> CJK_SYMBOL_ALTERNATIVES_TYPE
                HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE ->
                    IDEOGRAPHIC_ALTERNATIVES_TYPE
                HB_AAT_LAYOUT_FEATURE_TYPE_CJK_VERTICAL_ROMAN_PLACEMENT_TYPE ->
                    CJK_VERTICAL_ROMAN_PLACEMENT_TYPE
                HB_AAT_LAYOUT_FEATURE_TYPE_ITALIC_CJK_ROMAN -> ITALIC_CJK_ROMAN
                HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT -> CASE_SENSITIVE_LAYOUT
                HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA -> ALTERNATE_KANA
                HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES -> STYLISTIC_ALTERNATIVES
                HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES -> CONTEXTUAL_ALTERNATIVES
                HB_AAT_LAYOUT_FEATURE_TYPE_LOWER_CASE -> LOWER_CASE
                HB_AAT_LAYOUT_FEATURE_TYPE_UPPER_CASE -> UPPER_CASE
                HB_AAT_LAYOUT_FEATURE_TYPE_LANGUAGE_TAG_TYPE -> LANGUAGE_TAG_TYPE
                HB_AAT_LAYOUT_FEATURE_TYPE_CJK_ROMAN_SPACING_TYPE -> CJK_ROMAN_SPACING_TYPE
                else -> error("invalid nativeValue")
            }
    }
}
