// This is a generated file. Do not modify.
package org.gtkkn.bindings.harfbuzz

import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_ACCENT_BASE_HEIGHT
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_AXIS_HEIGHT
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_DELIMITED_SUB_FORMULA_MIN_HEIGHT
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_DISPLAY_OPERATOR_MIN_HEIGHT
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_FLATTENED_ACCENT_BASE_HEIGHT
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_FRACTION_DENOMINATOR_DISPLAY_STYLE_SHIFT_DOWN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_FRACTION_DENOMINATOR_GAP_MIN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_FRACTION_DENOMINATOR_SHIFT_DOWN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_FRACTION_DENOM_DISPLAY_STYLE_GAP_MIN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_FRACTION_NUMERATOR_DISPLAY_STYLE_SHIFT_UP
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_FRACTION_NUMERATOR_GAP_MIN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_FRACTION_NUMERATOR_SHIFT_UP
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_FRACTION_NUM_DISPLAY_STYLE_GAP_MIN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_FRACTION_RULE_THICKNESS
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_LOWER_LIMIT_BASELINE_DROP_MIN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_LOWER_LIMIT_GAP_MIN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_MATH_LEADING
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_OVERBAR_EXTRA_ASCENDER
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_OVERBAR_RULE_THICKNESS
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_OVERBAR_VERTICAL_GAP
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_RADICAL_DEGREE_BOTTOM_RAISE_PERCENT
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_RADICAL_DISPLAY_STYLE_VERTICAL_GAP
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_RADICAL_EXTRA_ASCENDER
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_RADICAL_KERN_AFTER_DEGREE
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_RADICAL_KERN_BEFORE_DEGREE
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_RADICAL_RULE_THICKNESS
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_RADICAL_VERTICAL_GAP
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_SCRIPT_PERCENT_SCALE_DOWN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_SCRIPT_SCRIPT_PERCENT_SCALE_DOWN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_SKEWED_FRACTION_HORIZONTAL_GAP
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_SKEWED_FRACTION_VERTICAL_GAP
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_SPACE_AFTER_SCRIPT
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_STACK_BOTTOM_DISPLAY_STYLE_SHIFT_DOWN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_STACK_BOTTOM_SHIFT_DOWN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_STACK_DISPLAY_STYLE_GAP_MIN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_STACK_GAP_MIN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_STACK_TOP_DISPLAY_STYLE_SHIFT_UP
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_STACK_TOP_SHIFT_UP
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_STRETCH_STACK_BOTTOM_SHIFT_DOWN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_STRETCH_STACK_GAP_ABOVE_MIN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_STRETCH_STACK_GAP_BELOW_MIN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_STRETCH_STACK_TOP_SHIFT_UP
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_SUBSCRIPT_BASELINE_DROP_MIN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_SUBSCRIPT_SHIFT_DOWN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_SUBSCRIPT_TOP_MAX
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_SUB_SUPERSCRIPT_GAP_MIN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_SUPERSCRIPT_BASELINE_DROP_MAX
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_SUPERSCRIPT_BOTTOM_MAX_WITH_SUBSCRIPT
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_SUPERSCRIPT_BOTTOM_MIN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_SUPERSCRIPT_SHIFT_UP
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_SUPERSCRIPT_SHIFT_UP_CRAMPED
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_UNDERBAR_EXTRA_DESCENDER
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_UNDERBAR_RULE_THICKNESS
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_UNDERBAR_VERTICAL_GAP
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_UPPER_LIMIT_BASELINE_RISE_MIN
import org.gtkkn.native.harfbuzz.hb_ot_math_constant_t.HB_OT_MATH_CONSTANT_UPPER_LIMIT_GAP_MIN

/**
 * The 'MATH' table constants specified at
 * https://docs.microsoft.com/en-us/typography/opentype/spec/math
 * @since 1.3.3
 */
public enum class OtMathConstant(
    public val nativeValue: hb_ot_math_constant_t,
) {
    SCRIPT_PERCENT_SCALE_DOWN(HB_OT_MATH_CONSTANT_SCRIPT_PERCENT_SCALE_DOWN),
    SCRIPT_SCRIPT_PERCENT_SCALE_DOWN(HB_OT_MATH_CONSTANT_SCRIPT_SCRIPT_PERCENT_SCALE_DOWN),
    DELIMITED_SUB_FORMULA_MIN_HEIGHT(HB_OT_MATH_CONSTANT_DELIMITED_SUB_FORMULA_MIN_HEIGHT),
    DISPLAY_OPERATOR_MIN_HEIGHT(HB_OT_MATH_CONSTANT_DISPLAY_OPERATOR_MIN_HEIGHT),
    MATH_LEADING(HB_OT_MATH_CONSTANT_MATH_LEADING),
    AXIS_HEIGHT(HB_OT_MATH_CONSTANT_AXIS_HEIGHT),
    ACCENT_BASE_HEIGHT(HB_OT_MATH_CONSTANT_ACCENT_BASE_HEIGHT),
    FLATTENED_ACCENT_BASE_HEIGHT(HB_OT_MATH_CONSTANT_FLATTENED_ACCENT_BASE_HEIGHT),
    SUBSCRIPT_SHIFT_DOWN(HB_OT_MATH_CONSTANT_SUBSCRIPT_SHIFT_DOWN),
    SUBSCRIPT_TOP_MAX(HB_OT_MATH_CONSTANT_SUBSCRIPT_TOP_MAX),
    SUBSCRIPT_BASELINE_DROP_MIN(HB_OT_MATH_CONSTANT_SUBSCRIPT_BASELINE_DROP_MIN),
    SUPERSCRIPT_SHIFT_UP(HB_OT_MATH_CONSTANT_SUPERSCRIPT_SHIFT_UP),
    SUPERSCRIPT_SHIFT_UP_CRAMPED(HB_OT_MATH_CONSTANT_SUPERSCRIPT_SHIFT_UP_CRAMPED),
    SUPERSCRIPT_BOTTOM_MIN(HB_OT_MATH_CONSTANT_SUPERSCRIPT_BOTTOM_MIN),
    SUPERSCRIPT_BASELINE_DROP_MAX(HB_OT_MATH_CONSTANT_SUPERSCRIPT_BASELINE_DROP_MAX),
    SUB_SUPERSCRIPT_GAP_MIN(HB_OT_MATH_CONSTANT_SUB_SUPERSCRIPT_GAP_MIN),
    SUPERSCRIPT_BOTTOM_MAX_WITH_SUBSCRIPT(HB_OT_MATH_CONSTANT_SUPERSCRIPT_BOTTOM_MAX_WITH_SUBSCRIPT),
    SPACE_AFTER_SCRIPT(HB_OT_MATH_CONSTANT_SPACE_AFTER_SCRIPT),
    UPPER_LIMIT_GAP_MIN(HB_OT_MATH_CONSTANT_UPPER_LIMIT_GAP_MIN),
    UPPER_LIMIT_BASELINE_RISE_MIN(HB_OT_MATH_CONSTANT_UPPER_LIMIT_BASELINE_RISE_MIN),
    LOWER_LIMIT_GAP_MIN(HB_OT_MATH_CONSTANT_LOWER_LIMIT_GAP_MIN),
    LOWER_LIMIT_BASELINE_DROP_MIN(HB_OT_MATH_CONSTANT_LOWER_LIMIT_BASELINE_DROP_MIN),
    STACK_TOP_SHIFT_UP(HB_OT_MATH_CONSTANT_STACK_TOP_SHIFT_UP),
    STACK_TOP_DISPLAY_STYLE_SHIFT_UP(HB_OT_MATH_CONSTANT_STACK_TOP_DISPLAY_STYLE_SHIFT_UP),
    STACK_BOTTOM_SHIFT_DOWN(HB_OT_MATH_CONSTANT_STACK_BOTTOM_SHIFT_DOWN),
    STACK_BOTTOM_DISPLAY_STYLE_SHIFT_DOWN(HB_OT_MATH_CONSTANT_STACK_BOTTOM_DISPLAY_STYLE_SHIFT_DOWN),
    STACK_GAP_MIN(HB_OT_MATH_CONSTANT_STACK_GAP_MIN),
    STACK_DISPLAY_STYLE_GAP_MIN(HB_OT_MATH_CONSTANT_STACK_DISPLAY_STYLE_GAP_MIN),
    STRETCH_STACK_TOP_SHIFT_UP(HB_OT_MATH_CONSTANT_STRETCH_STACK_TOP_SHIFT_UP),
    STRETCH_STACK_BOTTOM_SHIFT_DOWN(HB_OT_MATH_CONSTANT_STRETCH_STACK_BOTTOM_SHIFT_DOWN),
    STRETCH_STACK_GAP_ABOVE_MIN(HB_OT_MATH_CONSTANT_STRETCH_STACK_GAP_ABOVE_MIN),
    STRETCH_STACK_GAP_BELOW_MIN(HB_OT_MATH_CONSTANT_STRETCH_STACK_GAP_BELOW_MIN),
    FRACTION_NUMERATOR_SHIFT_UP(HB_OT_MATH_CONSTANT_FRACTION_NUMERATOR_SHIFT_UP),
    FRACTION_NUMERATOR_DISPLAY_STYLE_SHIFT_UP(HB_OT_MATH_CONSTANT_FRACTION_NUMERATOR_DISPLAY_STYLE_SHIFT_UP),
    FRACTION_DENOMINATOR_SHIFT_DOWN(HB_OT_MATH_CONSTANT_FRACTION_DENOMINATOR_SHIFT_DOWN),
    FRACTION_DENOMINATOR_DISPLAY_STYLE_SHIFT_DOWN(HB_OT_MATH_CONSTANT_FRACTION_DENOMINATOR_DISPLAY_STYLE_SHIFT_DOWN),
    FRACTION_NUMERATOR_GAP_MIN(HB_OT_MATH_CONSTANT_FRACTION_NUMERATOR_GAP_MIN),
    FRACTION_NUM_DISPLAY_STYLE_GAP_MIN(HB_OT_MATH_CONSTANT_FRACTION_NUM_DISPLAY_STYLE_GAP_MIN),
    FRACTION_RULE_THICKNESS(HB_OT_MATH_CONSTANT_FRACTION_RULE_THICKNESS),
    FRACTION_DENOMINATOR_GAP_MIN(HB_OT_MATH_CONSTANT_FRACTION_DENOMINATOR_GAP_MIN),
    FRACTION_DENOM_DISPLAY_STYLE_GAP_MIN(HB_OT_MATH_CONSTANT_FRACTION_DENOM_DISPLAY_STYLE_GAP_MIN),
    SKEWED_FRACTION_HORIZONTAL_GAP(HB_OT_MATH_CONSTANT_SKEWED_FRACTION_HORIZONTAL_GAP),
    SKEWED_FRACTION_VERTICAL_GAP(HB_OT_MATH_CONSTANT_SKEWED_FRACTION_VERTICAL_GAP),
    OVERBAR_VERTICAL_GAP(HB_OT_MATH_CONSTANT_OVERBAR_VERTICAL_GAP),
    OVERBAR_RULE_THICKNESS(HB_OT_MATH_CONSTANT_OVERBAR_RULE_THICKNESS),
    OVERBAR_EXTRA_ASCENDER(HB_OT_MATH_CONSTANT_OVERBAR_EXTRA_ASCENDER),
    UNDERBAR_VERTICAL_GAP(HB_OT_MATH_CONSTANT_UNDERBAR_VERTICAL_GAP),
    UNDERBAR_RULE_THICKNESS(HB_OT_MATH_CONSTANT_UNDERBAR_RULE_THICKNESS),
    UNDERBAR_EXTRA_DESCENDER(HB_OT_MATH_CONSTANT_UNDERBAR_EXTRA_DESCENDER),
    RADICAL_VERTICAL_GAP(HB_OT_MATH_CONSTANT_RADICAL_VERTICAL_GAP),
    RADICAL_DISPLAY_STYLE_VERTICAL_GAP(HB_OT_MATH_CONSTANT_RADICAL_DISPLAY_STYLE_VERTICAL_GAP),
    RADICAL_RULE_THICKNESS(HB_OT_MATH_CONSTANT_RADICAL_RULE_THICKNESS),
    RADICAL_EXTRA_ASCENDER(HB_OT_MATH_CONSTANT_RADICAL_EXTRA_ASCENDER),
    RADICAL_KERN_BEFORE_DEGREE(HB_OT_MATH_CONSTANT_RADICAL_KERN_BEFORE_DEGREE),
    RADICAL_KERN_AFTER_DEGREE(HB_OT_MATH_CONSTANT_RADICAL_KERN_AFTER_DEGREE),
    RADICAL_DEGREE_BOTTOM_RAISE_PERCENT(HB_OT_MATH_CONSTANT_RADICAL_DEGREE_BOTTOM_RAISE_PERCENT),
    ;

    public companion object {
        public fun fromNativeValue(nativeValue: hb_ot_math_constant_t): OtMathConstant =
            when (nativeValue) {
                HB_OT_MATH_CONSTANT_SCRIPT_PERCENT_SCALE_DOWN -> SCRIPT_PERCENT_SCALE_DOWN
                HB_OT_MATH_CONSTANT_SCRIPT_SCRIPT_PERCENT_SCALE_DOWN -> SCRIPT_SCRIPT_PERCENT_SCALE_DOWN
                HB_OT_MATH_CONSTANT_DELIMITED_SUB_FORMULA_MIN_HEIGHT -> DELIMITED_SUB_FORMULA_MIN_HEIGHT
                HB_OT_MATH_CONSTANT_DISPLAY_OPERATOR_MIN_HEIGHT -> DISPLAY_OPERATOR_MIN_HEIGHT
                HB_OT_MATH_CONSTANT_MATH_LEADING -> MATH_LEADING
                HB_OT_MATH_CONSTANT_AXIS_HEIGHT -> AXIS_HEIGHT
                HB_OT_MATH_CONSTANT_ACCENT_BASE_HEIGHT -> ACCENT_BASE_HEIGHT
                HB_OT_MATH_CONSTANT_FLATTENED_ACCENT_BASE_HEIGHT -> FLATTENED_ACCENT_BASE_HEIGHT
                HB_OT_MATH_CONSTANT_SUBSCRIPT_SHIFT_DOWN -> SUBSCRIPT_SHIFT_DOWN
                HB_OT_MATH_CONSTANT_SUBSCRIPT_TOP_MAX -> SUBSCRIPT_TOP_MAX
                HB_OT_MATH_CONSTANT_SUBSCRIPT_BASELINE_DROP_MIN -> SUBSCRIPT_BASELINE_DROP_MIN
                HB_OT_MATH_CONSTANT_SUPERSCRIPT_SHIFT_UP -> SUPERSCRIPT_SHIFT_UP
                HB_OT_MATH_CONSTANT_SUPERSCRIPT_SHIFT_UP_CRAMPED -> SUPERSCRIPT_SHIFT_UP_CRAMPED
                HB_OT_MATH_CONSTANT_SUPERSCRIPT_BOTTOM_MIN -> SUPERSCRIPT_BOTTOM_MIN
                HB_OT_MATH_CONSTANT_SUPERSCRIPT_BASELINE_DROP_MAX -> SUPERSCRIPT_BASELINE_DROP_MAX
                HB_OT_MATH_CONSTANT_SUB_SUPERSCRIPT_GAP_MIN -> SUB_SUPERSCRIPT_GAP_MIN
                HB_OT_MATH_CONSTANT_SUPERSCRIPT_BOTTOM_MAX_WITH_SUBSCRIPT ->
                    SUPERSCRIPT_BOTTOM_MAX_WITH_SUBSCRIPT
                HB_OT_MATH_CONSTANT_SPACE_AFTER_SCRIPT -> SPACE_AFTER_SCRIPT
                HB_OT_MATH_CONSTANT_UPPER_LIMIT_GAP_MIN -> UPPER_LIMIT_GAP_MIN
                HB_OT_MATH_CONSTANT_UPPER_LIMIT_BASELINE_RISE_MIN -> UPPER_LIMIT_BASELINE_RISE_MIN
                HB_OT_MATH_CONSTANT_LOWER_LIMIT_GAP_MIN -> LOWER_LIMIT_GAP_MIN
                HB_OT_MATH_CONSTANT_LOWER_LIMIT_BASELINE_DROP_MIN -> LOWER_LIMIT_BASELINE_DROP_MIN
                HB_OT_MATH_CONSTANT_STACK_TOP_SHIFT_UP -> STACK_TOP_SHIFT_UP
                HB_OT_MATH_CONSTANT_STACK_TOP_DISPLAY_STYLE_SHIFT_UP -> STACK_TOP_DISPLAY_STYLE_SHIFT_UP
                HB_OT_MATH_CONSTANT_STACK_BOTTOM_SHIFT_DOWN -> STACK_BOTTOM_SHIFT_DOWN
                HB_OT_MATH_CONSTANT_STACK_BOTTOM_DISPLAY_STYLE_SHIFT_DOWN ->
                    STACK_BOTTOM_DISPLAY_STYLE_SHIFT_DOWN
                HB_OT_MATH_CONSTANT_STACK_GAP_MIN -> STACK_GAP_MIN
                HB_OT_MATH_CONSTANT_STACK_DISPLAY_STYLE_GAP_MIN -> STACK_DISPLAY_STYLE_GAP_MIN
                HB_OT_MATH_CONSTANT_STRETCH_STACK_TOP_SHIFT_UP -> STRETCH_STACK_TOP_SHIFT_UP
                HB_OT_MATH_CONSTANT_STRETCH_STACK_BOTTOM_SHIFT_DOWN -> STRETCH_STACK_BOTTOM_SHIFT_DOWN
                HB_OT_MATH_CONSTANT_STRETCH_STACK_GAP_ABOVE_MIN -> STRETCH_STACK_GAP_ABOVE_MIN
                HB_OT_MATH_CONSTANT_STRETCH_STACK_GAP_BELOW_MIN -> STRETCH_STACK_GAP_BELOW_MIN
                HB_OT_MATH_CONSTANT_FRACTION_NUMERATOR_SHIFT_UP -> FRACTION_NUMERATOR_SHIFT_UP
                HB_OT_MATH_CONSTANT_FRACTION_NUMERATOR_DISPLAY_STYLE_SHIFT_UP ->
                    FRACTION_NUMERATOR_DISPLAY_STYLE_SHIFT_UP
                HB_OT_MATH_CONSTANT_FRACTION_DENOMINATOR_SHIFT_DOWN -> FRACTION_DENOMINATOR_SHIFT_DOWN
                HB_OT_MATH_CONSTANT_FRACTION_DENOMINATOR_DISPLAY_STYLE_SHIFT_DOWN ->
                    FRACTION_DENOMINATOR_DISPLAY_STYLE_SHIFT_DOWN
                HB_OT_MATH_CONSTANT_FRACTION_NUMERATOR_GAP_MIN -> FRACTION_NUMERATOR_GAP_MIN
                HB_OT_MATH_CONSTANT_FRACTION_NUM_DISPLAY_STYLE_GAP_MIN ->
                    FRACTION_NUM_DISPLAY_STYLE_GAP_MIN
                HB_OT_MATH_CONSTANT_FRACTION_RULE_THICKNESS -> FRACTION_RULE_THICKNESS
                HB_OT_MATH_CONSTANT_FRACTION_DENOMINATOR_GAP_MIN -> FRACTION_DENOMINATOR_GAP_MIN
                HB_OT_MATH_CONSTANT_FRACTION_DENOM_DISPLAY_STYLE_GAP_MIN ->
                    FRACTION_DENOM_DISPLAY_STYLE_GAP_MIN
                HB_OT_MATH_CONSTANT_SKEWED_FRACTION_HORIZONTAL_GAP -> SKEWED_FRACTION_HORIZONTAL_GAP
                HB_OT_MATH_CONSTANT_SKEWED_FRACTION_VERTICAL_GAP -> SKEWED_FRACTION_VERTICAL_GAP
                HB_OT_MATH_CONSTANT_OVERBAR_VERTICAL_GAP -> OVERBAR_VERTICAL_GAP
                HB_OT_MATH_CONSTANT_OVERBAR_RULE_THICKNESS -> OVERBAR_RULE_THICKNESS
                HB_OT_MATH_CONSTANT_OVERBAR_EXTRA_ASCENDER -> OVERBAR_EXTRA_ASCENDER
                HB_OT_MATH_CONSTANT_UNDERBAR_VERTICAL_GAP -> UNDERBAR_VERTICAL_GAP
                HB_OT_MATH_CONSTANT_UNDERBAR_RULE_THICKNESS -> UNDERBAR_RULE_THICKNESS
                HB_OT_MATH_CONSTANT_UNDERBAR_EXTRA_DESCENDER -> UNDERBAR_EXTRA_DESCENDER
                HB_OT_MATH_CONSTANT_RADICAL_VERTICAL_GAP -> RADICAL_VERTICAL_GAP
                HB_OT_MATH_CONSTANT_RADICAL_DISPLAY_STYLE_VERTICAL_GAP ->
                    RADICAL_DISPLAY_STYLE_VERTICAL_GAP
                HB_OT_MATH_CONSTANT_RADICAL_RULE_THICKNESS -> RADICAL_RULE_THICKNESS
                HB_OT_MATH_CONSTANT_RADICAL_EXTRA_ASCENDER -> RADICAL_EXTRA_ASCENDER
                HB_OT_MATH_CONSTANT_RADICAL_KERN_BEFORE_DEGREE -> RADICAL_KERN_BEFORE_DEGREE
                HB_OT_MATH_CONSTANT_RADICAL_KERN_AFTER_DEGREE -> RADICAL_KERN_AFTER_DEGREE
                HB_OT_MATH_CONSTANT_RADICAL_DEGREE_BOTTOM_RAISE_PERCENT ->
                    RADICAL_DEGREE_BOTTOM_RAISE_PERCENT
                else -> error("invalid nativeValue")
            }
    }
}
