.build-base:
  tags:
    - saas-linux-xlarge-amd64
  before_script:
    - echo "Running on Linux amd64. Started by ${GITLAB_USER_NAME} (@${GITLAB_USER_LOGIN})"
    - GRADLE_USER_HOME="$(pwd)/.gradle"
    - export GRADLE_USER_HOME
    - mkdir -p $GRADLE_USER_HOME ; cp .ci/ci-gradle.properties $GRADLE_USER_HOME/gradle.properties
    - ./gradlew javaToolchains

.build-base-macos:
  tags:
    - saas-macos-large-m2pro
  variables:
    HOMEBREW_NO_AUTO_UPDATE: "1"
  before_script:
    - echo "Running on macOS. Started by ${GITLAB_USER_NAME} (@${GITLAB_USER_LOGIN})"
    - ./.ci/install_macos_deps.sh
    - sudo ln -sfn $(brew --prefix)/opt/openjdk@17/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-17.jdk
    - export PATH="$(brew --prefix)/opt/openjdk@17/bin:$PATH"
    - export JAVA_HOME="$(brew --prefix)/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home/"
    - export JDK_HOME=${JAVA_HOME}
    - export JRE_HOME=${JDK_HOME}/jre/
    - GRADLE_USER_HOME="$(pwd)/.gradle"
    - export GRADLE_USER_HOME
    - mkdir -p $GRADLE_USER_HOME ; cp .ci/ci-gradle.properties $GRADLE_USER_HOME/gradle.properties
    - ./gradlew javaToolchains
